CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK74M_FIRE", "weapons/cw_kk_ins2_rpk74m/rpk74m_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK74M_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_rpk74m/rpk74m_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BIPODDEPLOY", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BIPODRETRACT", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BOLTBACK", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_BOLTRELEASE", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_DEPLOYGROUNDHIT", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_EMPTY", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_ENDDEPLOYEDRELOAD", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_FETCHMAG", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_FIRESELECT", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGIN", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGOUT", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGOUTRATTLE", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_MAGRELEASE", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK74M_RATTLE", "weapons/cw_kk_ins2_rpk74m/handling/rpk74m_rattle.wav")