ITEM.name = "Droplet"
ITEM.model ="models/nasca/etherealsrp_artifacts/droplet.mdl"
ITEM.description = "Looks like tears."
ITEM.longdesc = "From the exterior looks like a tear-like shade compound with a glossy surface, covered in cracks. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5