ITEM.name = "Fireball"
ITEM.model ="models/nasca/etherealsrp_artifacts/fireball.mdl"
ITEM.description = "A ball of fire. Artifact."
ITEM.longdesc = "It is a spherical artifact made of red-colored crystal, created in the Burner anomaly. It has an unique property - it has a constant temperature of 75 degrees Fahrenheit/24 degrees Celsius, regardless of its surroundings. This allows it to absorb heat from its vicinity and to create a little pocket around the user which prevents the flames from damaging the body. Stability of temperature is the cause of another of its positive effects: it accelerates healing rate and stops bleeding. It will also protect the user from chemical burns. However, it is unrecommended to approach chemical and acid anomalies when in possession of the artifact as it will increase the adverse effects of acids and toxins in user's bloodstream. It also makes the user vulnerable to electrical currents. It is quite heavy due to high density of crystal-like material. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5