ITEM.name = "Nightstar"
ITEM.model ="models/nasca/etherealsrp_artifacts/nightstar.mdl"
ITEM.description = "Spikey yellow artifact. Glowing."
ITEM.longdesc = "This glowing artifact can generate a locally directed gravity field which increases its mass. For this reason, Nightstar is extremely heavy. It provides protection against acids as well as heat. Due to its beautiful inner core it is highly sought after by jewelers all over the world, however it is best to proceed with caution as unskilled treatment can cause the artifact to explode with power sufficient to level a small building. It is thus highly advised to perform the polishing by means of specialized machinery, which minimizes the probability of explosion. Moreover, only the outer core of the artifact emits radiation. Nightstar will also absorb toxic and chemical agents from the environment, which makes it a valuable artifact for artifact hunters, although the amount of toxicity absorbed is negligible. It is, however, relatively cheap and even stalkers with pretty tight budgets can afford it if opportunity to buy it arises. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 12500
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5