ITEM.name = "Battery"
ITEM.model ="models/nasca/etherealsrp_artifacts/battery.mdl"
ITEM.description = "An electric artifact."
ITEM.longdesc = "A heavy artifact with a unique geometrical shape, consisting of three bent bars connected to either end of the artifact. It is possible to attach power lines to the artifact, and when done, it outputs a low voltage current, however in the samples tested by scientists, there was seemingly no limit to the amperage of the current.\nScientists are very interested in this, as it could revolutionise battery and power generation technology."
--ITEM.longdesc = "It comprises electrostatic elements, but scientists have yet to determine the exact physical conditions required for its formation. The artifact is quite popular in the Zone and is valued by its residents and visitors alike for its energizing properties, although it has an adverse effect on the body when used for prolonged periods of time. One should take note, however, that this artifact hinders blood clotting and increases bleeding rate of open wounds. On the other hand, being a powerful resistor, it is well known for its ability to shield its user from lethal doses of electricity. This artifact is also extremely light and very portable. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8400
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.rarity = 4
ITEM.baseweight = 6.000
ITEM.varweight  = 2.500
