ITEM.name = "Firefly"
ITEM.model ="models/nasca/etherealsrp_artifacts/firefly.mdl"
ITEM.description = "Green and beautiful artifact."
ITEM.longdesc = "Firefly interacts with fields unknown to science, considerably speeding up regeneration of tissue and organs in living beings, as well as normalizing metabolic processes. This artifact can literally get a badly wounded stalker back on his feet in a matter of minutes. On the other hand, Firefly can spontaneously combust when exposed to potent heat sources. It also amplifies the harmful effects of both psy-fields and electro anomalies, and seems to drain stamina and decrease stamina recovery. However, it will absorb any and all deadly chemicals within one's body. Furthermore, it admirably protects against toxicity, and seems to inject neutralizing chemical agents into user's bloodstream, which negate the effects of toxins and nerve damage. For this reason, it is in high demand in military circles as it can make terrorist attacks with chemical or biological weapons more easily manageable. Extremely rare."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 65000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5