ITEM.name = "Kolobok"
ITEM.model ="models/nasca/etherealsrp_artifacts/kolobok.mdl"
ITEM.description = "Very spikey artifact."
ITEM.longdesc = "A relatively rare artifact forming in chemical areas, Kolobok is highly valued for its ability to heal most kinds of wounds and stop bleeding in a matter of minutes. For unknown reasons, scientists are spreading rumors among stalkers that the artifact modifies bearer's genetic code, which is unproven and should be regarded as conscious attempt at monopolizing the supply of the artifact by the scientific community. This does not, however, mean that it is completely harmless. One drawback of this artifact is the fact that it will increase electrical conductivity, so it is best to avoid electro anomalies when in possession of the artifact, especially since its negative effects are not balanced with positive ones. It will also reduce energy recovery, which is the result of its sharp needle-like appendages. The needles cause small and quickly healing wounds which bring constant pain and itch, thus reducing stamina. This artifact also weakens protection against psy-emissions produced by anomalies or mutants as well as from heat and acids due to its high flammability. Given its chemical origin, it is also well known for its ability to increase user's protection against toxicity. Lightweight and not too much of a burden to carry around. A very rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 40000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5