ITEM.name = "Slime"
ITEM.model ="models/nasca/etherealsrp_artifacts/slime.mdl"
ITEM.description = "Slimey."
ITEM.longdesc = "An artifact connected by threads of slime. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2450
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5