ITEM.name = "Soul"
ITEM.model ="models/nasca/etherealsrp_artifacts/soul.mdl"
ITEM.description = "Spherish, blue artifact."
ITEM.longdesc = "Soul is a unique organic artifact with properties just as unique - it secretes slimy goo that dramatically increases recovery rate of wounds. Thanks to its reasonable price and attractive appearance, this artifact is a valuable collector's item. Because of its organic nature, Soul is highly flammable and should not be carried near a campfire or most heat sources. It is known to spontaneously combust when exposed to temperature exceeding 60°C. The artifact provides a high level of toxic and chemical protection by absorbing chemical agents. It then uses them as basis for producing its gooey substance which, when applied to wounds, soothes the pain and speeds up healing process. On the other hand, Soul amplifies the effects of psy-waves and increases the damage of electricity to one's body. It is also known to drain power from its user. The artifact does not have high density and thus is not very heavy. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 25000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5