ITEM.name = "Stoneflower"
ITEM.model ="models/nasca/etherealsrp_artifacts/stoneflower.mdl"
ITEM.description = "Looks like its melted and ripped apart. Artifact."
ITEM.longdesc = "This artifact resembles melted cheese interspersed with sapphire-like stones. Only yellow outer shell of the artifact appears to give off radiation and by careful processing it is possible to extract the non-radioactive blue parts for jewelery and other industrial purposes. This is due to the fact that if cleaned properly and polished, sapphire comparison becomes much more explicit: the stones are as hard and durable as this beautiful gem. This quality of theirs and their appearance make them perfect gemstones and jewelers all over the world strive to have them in stock. The usefulness of the artifact, however, is not limited to its industrial applications. There is scientific evidence suggesting that sapphire-like stones effectively protect from toxicity, whereas the outer shell slightly increases resistance to heat. Due to its density the weight of artifact has increased beyond normal standards, and thus it is one of the heaviest anomalous creations in the Zone. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5