ITEM.name = "Snowflake"
ITEM.model ="models/nasca/etherealsrp_artifacts/snowflake.mdl"
ITEM.description = "This artifact features blue spikes."
ITEM.longdesc = "Also colloquially known as 'Radioactive Snowflake'. At first glance, this artifact resembles a white Kolobok. Some claim that it actually is a form of Kolobok as it greatly increases resistance to electric currents by creating its own electric field and absorbing electricity that passes through user's body. Thanks to its unique properties, the artifact can significantly increase the bearer's muscle tone, thus greatly improving stamina recovery. Due to its high radioactivity, stalkers in possession of it are sometimes jokingly referred to as 'Radioactive Snowflakes'. When faced with the decision whether to carry it on the belt during a mission, you have to carefully weigh its pros and cons: does it pay to have greater endurance and high protection against electricity at the cost of being constantly exposed to its deadly radiation? Even if you are determined to take it with you, it should be noted that it is not to be used on long excursions to the Zone. Its usefulness in a fight is also debatable as it increases bleeding rate and prevents wounds from closing due to its very sharp appendages which sting the user and irritate the skin. It is, however, as light as a snowflake and very easy to carry around. Very rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5