ITEM.name = "Shell"
ITEM.model ="models/nasca/etherealsrp_artifacts/shell.mdl"
ITEM.description = "Blue, semitransparent artifact."
ITEM.longdesc = "Shell is composed of two disk of bluish color connected by semitransparent material of unknown nature. This strange artifact was considered devoid of any useful properties by many scientists for a long time. Only recently has it been discovered that it is indeed quite beneficial. It provides a high level of psy protection and absorbs electromagnetic interference, acting as a grounding material. When the artifact comes into contact with the body, it will make one feel rejuvenated and thus it increases stamina recovery. This effect has in case of some stalkers induced hyperactivity. One downside of this artifact, however, is that it reduces the number of platelets in blood, thus increasing bleeding rate. Shell is extremely light and very portable. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 20000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5