ITEM.name = "Thorn"
ITEM.model ="models/nasca/etherealsrp_artifacts/thorn.mdl"
ITEM.description = "Spikey artifact, but quite small."
ITEM.longdesc = "The result of the interaction between the anomaly Burnt Fuzz and the body of a careless stalker. The Thorn artifact pokes the body of its owner, no matter what. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1250
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5