ITEM.name = "Wrenched"
ITEM.model ="models/nasca/etherealsrp_artifacts/wrenched.mdl"
ITEM.description = "Bizarre, whalelike artifact."
ITEM.longdesc = "This bizarrely-shaped artifact appears in places with increased gravitational activity. Acting as a kind of sponge that absorbs chemical and toxic elements, this artifact provides protection from external toxic agents as well as from chemical particles that have already made their way into the body. Although it appears almost organic, it is actually more similar to coral. Due to its non-organic nature, it is nonflammable. It provides protection against acids as well as heat. There is no particular faction that takes great interest in it, so it is mostly sold to scientists who study and experiment on the artifact in order to find the use for it. It has high density and is thus extremely heavy. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 22000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5