CustomizableWeaponry:addFireSound("CW_KK_INS2_GALIL_FIRE", "weapons/galil/galil_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_GALIL_FIRE_SUPPRESSED", "weapons/galil/galil_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_BOLTBACK", "weapons/galil/handling/galil_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_BOLTRELEASE", "weapons/galil/handling/galil_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_DRUM_MAGFETCH", "weapons/galil/handling/galil_drum_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_DRUM_MAGHIT", "weapons/galil/handling/galil_drum_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_DRUM_MAGIN", "weapons/galil/handling/galil_drum_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_DRUM_MAGOUT", "weapons/galil/handling/galil_drum_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_DRUM_MAGOUTRATTLE", "weapons/galil/handling/galil_drum_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_EMPTY", "weapons/galil/handling/galil_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_FIRESELECT", "weapons/galil/handling/galil_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_MAGIN", "weapons/galil/handling/galil_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_MAGOUT", "weapons/galil/handling/galil_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_MAGRELEASE", "weapons/galil/handling/galil_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_GALIL_RATTLE", "weapons/galil/handling/galil_rattle.wav")