CustomizableWeaponry:addFireSound("CW_KK_INS2_VECTOR_FIRE", "weapons/vector/mp5k_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_VECTOR_FIRE_SUPPRESSED", "weapons/vector/mp5k_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_BOLTBACK", "weapons/vector/handling/mp5k_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_BOLTLOCK", "weapons/vector/handling/mp5k_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_BOLTRELEASE", "weapons/vector/handling/mp5k_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_EMPTY", "weapons/vector/handling/mp5k_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_FIRESELECT", "weapons/vector/handling/mp5k_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_MAGIN", "weapons/vector/handling/mp5k_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_MAGOUT", "weapons/vector/handling/mp5k_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_VECTOR_MAGRELEASE", "weapons/vector/handling/mp5k_magrelease.wav")