
-- game.AddParticles("particles/cw_kk_ins2/ammo_cache_ins.pcf")
-- game.AddParticles("particles/cw_kk_ins2/blood_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/blood_impact.pcf")
-- game.AddParticles("particles/cw_kk_ins2/burning_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/environment_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/environmental_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/error.pcf")
game.AddParticles("particles/cw_kk_ins2/explosion_fx_ins.pcf")
game.AddParticles("particles/cw_kk_ins2/explosion_fx_ins_b.pcf")
-- game.AddParticles("particles/cw_kk_ins2/fire_01.pcf")
-- game.AddParticles("particles/cw_kk_ins2/fire_01_ins.pcf")
-- game.AddParticles("particles/cw_kk_ins2/fire_01_unused.pcf")
-- game.AddParticles("particles/cw_kk_ins2/fire_01l4d.pcf")
-- game.AddParticles("particles/cw_kk_ins2/flashlight.pcf")
-- game.AddParticles("particles/cw_kk_ins2/footstep_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/impact_fx_ins.pcf")
-- game.AddParticles("particles/cw_kk_ins2/ins_burning_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/ins_light_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/ins_rockettrail.pcf")
game.AddParticles("particles/cw_kk_ins2/ins_smokegrenade.pcf")
-- game.AddParticles("particles/cw_kk_ins2/insect_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/jonny_light_rigs.pcf")
-- game.AddParticles("particles/cw_kk_ins2/light_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/menu.pcf")
-- game.AddParticles("particles/cw_kk_ins2/rain_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/rain_fx_unused.pcf")
-- game.AddParticles("particles/cw_kk_ins2/rope_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/screen_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/snow_fx_unused.pcf")
-- game.AddParticles("particles/cw_kk_ins2/spark_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/steamworks.pcf")
-- game.AddParticles("particles/cw_kk_ins2/water_fx.pcf")
-- game.AddParticles("particles/cw_kk_ins2/water_impact.pcf")
-- game.AddParticles("particles/cw_kk_ins2/weapon_fx.pcf")
game.AddParticles("particles/cw_kk_ins2/weapon_fx_ins.pcf")
game.AddParticles("particles/cw_kk_ins2/weapon_fx_ins_b.pcf")
-- game.AddParticles("particles/cw_kk_ins2/weapon_fx_tracers.pcf")
-- game.AddParticles("particles/cw_kk_ins2/world_fx_ins.pcf")

-- game.AddParticles("particles/cw_kk_doi/asw_welding_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/blood_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/blood_impact.pcf")
-- game.AddParticles("particles/cw_kk_doi/burning_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/burningplayer.pcf")
-- game.AddParticles("particles/cw_kk_doi/burningplayer_dx80.pcf")
game.AddParticles("particles/cw_kk_doi/doi_explosion_fx.pcf")
game.AddParticles("particles/cw_kk_doi/doi_explosion_fx_b.pcf")
game.AddParticles("particles/cw_kk_doi/doi_explosions_smoke.pcf")
game.AddParticles("particles/cw_kk_doi/doi_impact_fx.pcf")
game.AddParticles("particles/cw_kk_doi/doi_weapon_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/environment_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/environmental_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/error.pcf")
-- game.AddParticles("particles/cw_kk_doi/explosion_fx_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/explosion_fx_ins_b.pcf")
-- game.AddParticles("particles/cw_kk_doi/fire_01.pcf")
-- game.AddParticles("particles/cw_kk_doi/fire_01_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/fire_01_unused.pcf")
-- game.AddParticles("particles/cw_kk_doi/fire_01l4d.pcf")
-- game.AddParticles("particles/cw_kk_doi/fire_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/flashlight.pcf")
-- game.AddParticles("particles/cw_kk_doi/footstep_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/impact_fx_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/ins_burning_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/ins_light_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/ins_rockettrail.pcf")
-- game.AddParticles("particles/cw_kk_doi/ins_smokegrenade.pcf")
-- game.AddParticles("particles/cw_kk_doi/insect_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/jonny_light_rigs.pcf")
-- game.AddParticles("particles/cw_kk_doi/light_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/menu.pcf")
-- game.AddParticles("particles/cw_kk_doi/mnb_fire.pcf")
game.AddParticles("particles/cw_kk_doi/mnb_flamethrower.pcf")
-- game.AddParticles("particles/cw_kk_doi/rain_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/rain_fx_unused.pcf")
-- game.AddParticles("particles/cw_kk_doi/rope_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/screen_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/snow_fx_unused.pcf")
-- game.AddParticles("particles/cw_kk_doi/spark_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/steamworks.pcf")
-- game.AddParticles("particles/cw_kk_doi/water_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/water_impact.pcf")
-- game.AddParticles("particles/cw_kk_doi/weapon_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/weapon_fx_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/weapon_fx_ins_b.pcf")
-- game.AddParticles("particles/cw_kk_doi/weapon_fx_tracers.pcf")
-- game.AddParticles("particles/cw_kk_doi/world_fx_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/ammo_cache_ins.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_environmental_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_muzzle_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_order_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_precipitation.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_spark_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_tracer_fx.pcf")
-- game.AddParticles("particles/cw_kk_doi/asw_weapon_fx.pcf")
