CustomizableWeaponry:addFireSound("CW_KK_INS2_M14_FIRE", "weapons/m14/m14_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M14_FIRE_SUPPRESSED", "weapons/m14/m14_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_BOLTBACK", "weapons/m14/handling/m14_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_BOLTRELEASE", "weapons/m14/handling/m14_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_EMPTY", "weapons/m14/handling/m14_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_FIRESELECT", "weapons/m14/handling/m14_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_MAGIN", "weapons/m14/handling/m14_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_MAGOUT", "weapons/m14/handling/m14_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_MAGOUTRATTLE", "weapons/m14/handling/m14_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_MAGRELEASE", "weapons/m14/handling/m14_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14_RATTLE", "weapons/m14/handling/m14_rattle.wav")