CustomizableWeaponry:addFireSound("CW_KK_INS2_M4A1CHAN_FIRE", "weapons/m4a1chan/moan_fire.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M4A1CHAN_FIRE_SUPPRESSED", "weapons/m4a1chan/moan_fire.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_BOLTBACK", "weapons/m4a1/handling/m4a1_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1CHAN_BOLTRELEASE", "weapons/m4a1chan/handling/m4a1_boltrelease_oniichan.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1CHAN_EMPTY", "weapons/m4a1chan/handling/m4a1_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_FIRESELECT", "weapons/m4a1/handling/m4a1_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1CHAN_HIT", "weapons/m4a1chan/handling/m4a1_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGHITRELEASE", "weapons/m4a1/handling/m4a1_maghitrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1CHAN_MAGIN", "weapons/m4a1chan/handling/m4a1_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1CHAN_MAGOUT", "weapons/m4a1chan/handling/m4a1_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGRELEASE", "weapons/m4a1/handling/m4a1_magrelease.wav")