/*
if (CLIENT) then
    function PLUGIN:PlayerButtonDown(client, key)
        -- Quick help menu
        if (key == KEY_F1) then
            if (client:GetCharacter() and not hook.Run("ShouldSuppressMenu", client) and not IsValid(ix.gui.menu)) then
                if client:IsSuperAdmin() then
                    local quickhelp = vgui.Create("ixMenu")
                    quickhelp.tabs.buttons[5]:SetSelected(true)
                elseif not client:IsSuperAdmin() then
                    local quickhelp = vgui.Create("ixMenu")
                    quickhelp.tabs.buttons[3]:SetSelected(true)
                end
            end
        end
    end
end
*/

function PLUGIN:PopulateHelpMenu(tabs)
    tabs["readme"] = function(container)
        local title = container:Add("DLabel")
        title:SetText("Welcome to Call of the Zone!")
        title:SetFont("stalkerregularbigfont")
        title:Dock(TOP)
        title:InvalidateLayout(true)
        title:SetAutoStretchVertical(true)
        local wip = container:Add("DLabel")
        wip:SetFont("stalkerregularsmallfont")
        wip:SetText("The server is in development, everything you see is work in progress!")
        wip:Dock(TOP)
        wip:SetAutoStretchVertical(true)
        local lore = container:Add("DLabel")
        lore:SetWrap(true)
        lore:SetFont("stalkerregularfont")
        lore:SetText("Call of the Zone is a gamemode where you are required to cooperate to survive the zone. Death is punishing, rewards are small, and you need to stick together and cooperate if you plan to get anywhere. The gamemode is a proof of concept for what we would like to think as a stalker multiplayer gamemode, and draws inspiration from many games and GMOD gamemodes. Atmosphere has it's highest focus, and the gameplay is supposed to be as optimized and smooth as possible.")
        lore:Dock(TOP)
        lore:DockMargin(0, 16, 0, 0)
        lore:SetAutoStretchVertical(true)
        local lore2 = container:Add("DLabel")
        lore2:SetFont("stalkerregularfont")
        lore2:SetText("You'll be moving forward as a playerbase as you do tasks for various NPC's to progress, and gain access to new NPC's, tasks and items. Hence, again, cooperation is heavily encouraged! Eventually you'll be able to unlock new zones for you to travel to.")
        lore2:Dock(TOP)
        lore2:DockMargin(0, 16, 0, 0)
        lore2:SetWrap(true)
        lore2:SetAutoStretchVertical(true)
        local lore3 = container:Add("DLabel")
        lore3:SetFont("stalkerregularfont")
        lore3:SetText("Lastly, we encourage you to explore and find out how many things work yourselves and share them with the community. We do on try to keep radio silence with most things as developers, and leave it up to you to uncover the secrets of the zone.")
        lore3:Dock(TOP)
        lore3:DockMargin(0, 16, 0, 0)
        lore3:SetWrap(true)
        lore3:SetAutoStretchVertical(true)
        local keys = container:Add("DLabel")
        keys:SetFont("stalkerregularfont")
        keys:SetText("Good luck, stalkers, and have fun!")
        keys:Dock(TOP)
        keys:DockMargin(0, 16, 0, 0)
        keys:SetWrap(true)
        keys:SetAutoStretchVertical(true)
    end

    tabs["keybinds"] = function(container)
        local title = container:Add("DLabel")
        title:SetText("Keybinds")
        title:SetFont("stalkerregularbigfont")
        title:Dock(TOP)
        title:InvalidateLayout(true)
        title:SetAutoStretchVertical(true)
        local note = container:Add("DLabel")
        note:SetFont("stalkerregularsmallfont")
        note:SetText("Listed below are certain gamemode related keybinds, you can not change most of them as of yet.")
        note:Dock(TOP)
        note:SetAutoStretchVertical(true)
        local category = container:Add("DLabel")
        category:SetWrap(true)
        category:SetFont("stalkerregularfontcategory")
        category:SetText("Function Keys")
        category:SetColor(Color(255, 255, 255, 100))
        category:Dock(TOP)
        category:DockMargin(0, 16, 0, 0)
        category:SetAutoStretchVertical(true)
        local function1 = container:Add("DLabel")
        function1:SetWrap(true)
        function1:SetFont("stalkerregularfont")
        function1:SetText(string.upper(input.LookupBinding("gm_showhelp", true)) .. " -  Use Hotkey 1 (gm_showhelp)")
        function1:Dock(TOP)
        function1:DockMargin(0, 16, 0, 0)
        function1:SetAutoStretchVertical(true)
        local function2 = container:Add("DLabel")
        function2:SetFont("stalkerregularfont")
        function2:SetText(string.upper(input.LookupBinding("gm_showteam", true)) .. " -  Use Hotkey 2 (gm_showteam)")
        function2:Dock(TOP)
        function2:DockMargin(0, 16, 0, 0)
        function2:SetWrap(true)
        function2:SetAutoStretchVertical(true)
        local function3 = container:Add("DLabel")
        function3:SetFont("stalkerregularfont")
        function3:SetText(string.upper(input.LookupBinding("gm_showspare1", true)) .. " -  Use Hotkey 3 (gm_showspare1)")
        function3:Dock(TOP)
        function3:DockMargin(0, 16, 0, 0)
        function3:SetWrap(true)
        function3:SetAutoStretchVertical(true)
        local function4 = container:Add("DLabel")
        function4:SetFont("stalkerregularfont")
        function4:SetText(string.upper(input.LookupBinding("gm_showspare2", true)) .. " -  Use Hotkey 4 (gm_showspare2)")
        function4:Dock(TOP)
        function4:DockMargin(0, 16, 0, 0)
        function4:SetWrap(true)
        function4:SetAutoStretchVertical(true)
        local category2 = container:Add("DLabel")
        category2:SetWrap(true)
        category2:SetFont("stalkerregularfontcategory")
        category2:SetText("Inventory")
        category2:SetColor(Color(255, 255, 255, 100))
        category2:Dock(TOP)
        category2:DockMargin(0, 16, 0, 0)
        category2:SetAutoStretchVertical(true)
        local inv = container:Add("DLabel")
        inv:SetFont("stalkerregularfont")
        inv:SetText("Left Click  -  Drag Item")
        inv:Dock(TOP)
        inv:DockMargin(0, 16, 0, 0)
        inv:SetWrap(true)
        inv:SetAutoStretchVertical(true)
        local inv2 = container:Add("DLabel")
        inv2:SetFont("stalkerregularfont")
        inv2:SetText("Right Click  -  Item Interaction Menu")
        inv2:Dock(TOP)
        inv2:DockMargin(0, 16, 0, 0)
        inv2:SetWrap(true)
        inv2:SetAutoStretchVertical(true)
        local inv3 = container:Add("DLabel")
        inv3:SetFont("stalkerregularfont")
        inv3:SetText("Shift + Right Click  -  Equip/Unequips Item")
        inv3:Dock(TOP)
        inv3:DockMargin(0, 16, 0, 0)
        inv3:SetWrap(true)
        inv3:SetAutoStretchVertical(true)
        local note2 = container:Add("DLabel")
        note2:SetFont("stalkerregulartipfont")
        note2:SetText("* Shift + Right Clicking on a Deck of Cards takes a card from the deck")
        note2:Dock(TOP)
        note2:SetAutoStretchVertical(true)
        local inv4 = container:Add("DLabel")
        inv4:SetFont("stalkerregularfont")
        inv4:SetText("Middle Click  -  Drops Item")
        inv4:Dock(TOP)
        inv4:DockMargin(0, 16, 0, 0)
        inv4:SetWrap(true)
        inv4:SetAutoStretchVertical(true)
        local category3 = container:Add("DLabel")
        category3:SetWrap(true)
        category3:SetFont("stalkerregularfontcategory")
        category3:SetText("Weapons")
        category3:SetColor(Color(255, 255, 255, 100))
        category3:Dock(TOP)
        category3:DockMargin(0, 16, 0, 0)
        category3:SetAutoStretchVertical(true)
        local wep = container:Add("DLabel")
        wep:SetFont("stalkerregularfont")
        wep:SetText("Hold " .. string.upper(input.LookupBinding("+reload", true)) .. "  -  Toggles Weapon Raise")
        wep:Dock(TOP)
        wep:DockMargin(0, 16, 0, 0)
        wep:SetWrap(true)
        wep:SetAutoStretchVertical(true)
        local wep2 = container:Add("DLabel")
        wep2:SetFont("stalkerregularfont")
        wep2:SetText(string.upper(input.LookupBinding("+menu_context", true)) .. "  -  Cycles Ammo Type")
        wep2:Dock(TOP)
        wep2:DockMargin(0, 16, 0, 0)
        wep2:SetWrap(true)
        wep2:SetAutoStretchVertical(true)
        local wep3 = container:Add("DLabel")
        wep3:SetFont("stalkerregularfont")
        wep3:SetText(string.upper(input.LookupBinding("+use", true)) .. " + " .. string.upper(input.LookupBinding("+reload", true)) .. "  -  Cycles Fire Mode")
        wep3:Dock(TOP)
        wep3:DockMargin(0, 16, 0, 0)
        wep3:SetWrap(true)
        wep3:SetAutoStretchVertical(true)
    end
end
