if (CLIENT) then
    function PLUGIN:PlayerButtonDown(client, key)
        -- Quick help menu
        if (key == KEY_F1) then
            if (client:GetCharacter() and not hook.Run("ShouldSuppressMenu", client) and not IsValid(ix.gui.menu)) then
                if client:IsSuperAdmin() then
                    local quickhelp = vgui.Create("ixMenu")
                    quickhelp.tabs.buttons[5]:SetSelected(true)
                elseif not client:IsSuperAdmin() then
                    local quickhelp = vgui.Create("ixMenu")
                    quickhelp.tabs.buttons[3]:SetSelected(true)
                end
            end
        end
    end
end

function PLUGIN:PopulateHelpMenu(tabs)
    tabs["readme"] = function(container)
        local title = container:Add("DLabel")
        title:SetText("Welcome to Call of the Zone!")
        title:SetFont("stalkerregularbigfont")
        title:Dock(TOP)
        title:InvalidateLayout(true)
        title:SetAutoStretchVertical(true)
        local wip = container:Add("DLabel")
        wip:SetFont("stalkerregularsmallfont")
        wip:SetText("The server is in development, everything you see is work in progress!")
        wip:Dock(TOP)
        wip:SetAutoStretchVertical(true)
        local lore = container:Add("DLabel")
        lore:SetWrap(true)
        lore:SetFont("stalkerregularfont")
        lore:SetText("Call of the Zone is a gamemode where you are required to cooperate to survive the zone. Death is punishing, rewards are small, and you need to stick together and cooperate if you plan to get anywhere. The gamemode is a proof of concept for what we would like to think as a stalker multiplayer gamemode, and draws inspiration from many games and GMOD gamemodes. Atmosphere has it's highest focus, and the gameplay is supposed to be as optimized and smooth as possible.")
        lore:Dock(TOP)
        lore:DockMargin(0, 16, 0, 0)
        lore:SetAutoStretchVertical(true)
        local lore2 = container:Add("DLabel")
        lore2:SetFont("stalkerregularfont")
        lore2:SetText("You'll be moving forward as a playerbase as you do tasks for various NPC's to progress, and gain access to new NPC's, tasks and items. Hence, again, cooperation is heavily encouraged! Eventually you'll be able to unlock new zones for you to travel to.")
        lore2:Dock(TOP)
        lore2:DockMargin(0, 16, 0, 0)
        lore2:SetWrap(true)
        lore2:SetAutoStretchVertical(true)
        local lore3 = container:Add("DLabel")
        lore3:SetFont("stalkerregularfont")
        lore3:SetText("Lastly, we encourage you to explore and find out how many things work yourselves and share them with the community. We do on try to keep radio silence with most things as developers, and leave it up to you to uncover the secrets of the zone.")
        lore3:Dock(TOP)
        lore3:DockMargin(0, 16, 0, 0)
        lore3:SetWrap(true)
        lore3:SetAutoStretchVertical(true)
        local keys = container:Add("DLabel")
        keys:SetFont("stalkerregularfont")
        keys:SetText("Don't die, as death resembles ironman mode without deleting your character. Good luck, stalkers, and have fun!")
        keys:Dock(TOP)
        keys:DockMargin(0, 16, 0, 0)
        keys:SetWrap(true)
        keys:SetAutoStretchVertical(true)
    end

    tabs["keybinds"] = function(container)
        local title = container:Add("DLabel")
        title:SetText("Keybinds")
        title:SetFont("stalkerregularbigfont")
        title:Dock(TOP)
        title:InvalidateLayout(true)
        title:SetAutoStretchVertical(true)
        local wip = container:Add("DLabel")
        wip:SetFont("stalkerregularsmallfont")
        wip:SetText("Listed below are certain gamemode related keybinds, you can not change them as of yet.")
        wip:Dock(TOP)
        wip:SetAutoStretchVertical(true)
        local category = container:Add("DLabel")
        category:SetWrap(true)
        category:SetFont("stalkerregularfontcategory")
        category:SetText("Function Keys")
        category:SetColor(Color(255, 255, 255, 100))
        category:Dock(TOP)
        category:DockMargin(0, 16, 0, 0)
        category:SetAutoStretchVertical(true)
        local lore = container:Add("DLabel")
        lore:SetWrap(true)
        lore:SetFont("stalkerregularfont")
        lore:SetText("F1  -  Quick Help Menu")
        lore:Dock(TOP)
        lore:DockMargin(0, 16, 0, 0)
        lore:SetAutoStretchVertical(true)
        local lore3 = container:Add("DLabel")
        lore3:SetFont("stalkerregularfont")
        lore3:SetText("F2  -  Toggles HUD")
        lore3:Dock(TOP)
        lore3:DockMargin(0, 16, 0, 0)
        lore3:SetWrap(true)
        lore3:SetAutoStretchVertical(true)
        local keys = container:Add("DLabel")
        keys:SetFont("stalkerregularfont")
        keys:SetText(input.LookupBinding( "gm_showspare1", true ) .. "  -  Voice Mode Menu")
        keys:Dock(TOP)
        keys:DockMargin(0, 16, 0, 0)
        keys:SetWrap(true)
        keys:SetAutoStretchVertical(true)
        local key4 = container:Add("DLabel")
        key4:SetFont("stalkerregularfont")
        key4:SetText("F4  -  Toggles Thirdperson")
        key4:Dock(TOP)
        key4:DockMargin(0, 16, 0, 4)
        key4:SetWrap(true)
        key4:SetAutoStretchVertical(true)
        keys:SetAutoStretchVertical(true)
        local category2 = container:Add("DLabel")
        category2:SetWrap(true)
        category2:SetFont("stalkerregularfontcategory")
        category2:SetText("Inventory")
        category2:SetColor(Color(255, 255, 255, 100))
        category2:Dock(TOP)
        category2:DockMargin(0, 16, 0, 0)
        category2:SetAutoStretchVertical(true)
        local inv = container:Add("DLabel")
        inv:SetFont("stalkerregularfont")
        inv:SetText("Left Click  -  Drag Item")
        inv:Dock(TOP)
        inv:DockMargin(0, 16, 0, 0)
        inv:SetWrap(true)
        inv:SetAutoStretchVertical(true)
        local inv2 = container:Add("DLabel")
        inv2:SetFont("stalkerregularfont")
        inv2:SetText("Right Click  -  Item Interaction Menu")
        inv2:Dock(TOP)
        inv2:DockMargin(0, 16, 0, 0)
        inv2:SetWrap(true)
        inv2:SetAutoStretchVertical(true)
        local inv3 = container:Add("DLabel")
        inv3:SetFont("stalkerregularfont")
        inv3:SetText("Shift + Right Click  -  Equip/Unequips Item")
        inv3:Dock(TOP)
        inv3:DockMargin(0, 16, 0, 0)
        inv3:SetWrap(true)
        inv3:SetAutoStretchVertical(true)
        local note2 = container:Add("DLabel")
        note2:SetFont("stalkerregulartipfont")
        note2:SetText("* Shift + Right Clicking on a Deck of Cards takes a card from the deck")
        note2:Dock(TOP)
        note2:SetAutoStretchVertical(true)
        local inv4 = container:Add("DLabel")
        inv4:SetFont("stalkerregularfont")
        inv4:SetText("Middle Click  -  Drops Item")
        inv4:Dock(TOP)
        inv4:DockMargin(0, 16, 0, 0)
        inv4:SetWrap(true)
        inv4:SetAutoStretchVertical(true)
    end
end
