CustomizableWeaponry:addFireSound("CW_KK_INS2_FNFAL_FIRE", "weapons/fnfal/fnfal_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_FNFAL_FIRE_SUPPRESSED", "weapons/fnfal/fnfal_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_BOLTBACK", "weapons/fnfal/handling/fnfal_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_BOLTRELEASE", "weapons/fnfal/handling/fnfal_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_EMPTY", "weapons/fnfal/handling/fnfal_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_FIRESELECT", "weapons/fnfal/handling/fnfal_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGIN", "weapons/fnfal/handling/fnfal_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGOUT", "weapons/fnfal/handling/fnfal_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGOUTRATTLE", "weapons/fnfal/handling/fnfal_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGRELEASE", "weapons/fnfal/handling/fnfal_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_RATTLE", "weapons/fnfal/handling/fnfal_rattle.wav")
