// Put the allowed items for the quick menus here.
PLUGIN.hotkeyitems = {
    ["medic_medkit_1"] = "use",
    ["medic_medkit_2"] = "use",
    ["medic_medkit_3"] = "use",
    ["medic_medkit_4"] = "use",
    ["medic_medkit_5"] = "use",
    ["medic_medkit_6"] = "use",

    ["medic_bandage_1"] = "use",
    ["medic_bandage_2"] = "use",
    ["medic_bandage_3"] = "use",

    ["medic_stimpak_1"] = "use",
    ["medic_stimpak_2"] = "use",
    ["medic_stimpak_3"] = "use",

    ["medic_antirad_1"] = "use",
    ["medic_antirad_2"] = "use",

    ["medic_antipsychotic_1"] = "use",
    ["medic_antipsychotic_2"] = "use",
    ["medic_antipsychotic_3"] = "use",

    ["medic_psyheal_1"] = "use",
    ["medic_psyheal_2"] = "use",
    
    ["drug_adrenaline"] = "use",
    ["drug_morphine"] = "use",
    ["drug_painkillers"] = "use",
    ["drug_caffeine"] = "use",
    ["drug_marijuana"] = "use",
    ["drug_mints"] = "use",
    ["miscaid_swampbrew"] = "use",
    
    --Drinks
    ["drink_bottlebeer_1"] = "use",
    ["drink_bottlebeer_2"] = "use",
    ["drink_bottlebeer_3"] = "use",
    ["drink_bottlebeer_4"] = "use",
    ["drink_bottlebeer_5"] = "use",
    ["drink_bottlebeer_6"] = "use",
    ["drink_bottletea"] = "use",
    ["drink_bottlewater"] = "use",
    ["drink_bottlewaterdirty"] = "use",
    ["drink_canwater"] = "use",
    ["drink_canbeer_1"] = "use",
    ["drink_canbeer_2"] = "use",
    ["drink_canbeer_3"] = "use",
    ["drink_canbeer_4"] = "use",
    ["drink_canbeer_5"] = "use",
    ["drink_canbeer_6"] = "use",
    ["drink_energydrink_1"] = "use",
    ["drink_energydrink_2"] = "use",
    ["drink_energydrink_3"] = "use",
    ["drink_energydrink_4"] = "use",
    ["drink_energydrink_5"] = "use",
    ["drink_energydrink_6"] = "use",
    ["drink_milk"] = "use",
    ["drink_milkold"] = "use",
    ["drink_moonshine"] = "use",
    ["drink_orangejuice"] = "use",
    ["drink_spirit_1"] = "use",
    ["drink_spirit_2"] = "use",
    ["drink_spirit_3"] = "use",
    ["drink_vodka_1"] = "use",
    ["drink_vodka_2"] = "use",
    ["drink_vodka_3"] = "use",
    ["drink_vodka_4"] = "use",
    ["drink_vodka_5"] = "use",
    ["drink_vodka_6"] = "use",
    ["drink_wine"] = "use",
    
    --hidestashers (unhide only)
    ["hidestasher_cleaningkit"] = "unhidestash",
    ["hidestasher_cutlery"] = "unhidestash",
    ["hidestasher_shovel"] = "unhidestash",
}