ITEM.name = "Anomaly map"
ITEM.description = "Handdrawn by an unknown stalker. Useless, as the locations change between blowouts."
ITEM.model = "models/kek1ch/notes_letter_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 500
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05