ITEM.name = "Anomaly Research Documents (simple)"
ITEM.description = "Describes different anomalies. Only covers the most common anomalies."
ITEM.model = "models/kek1ch/notes_paper_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "2150"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05