ITEM.name = "Personal Belongings"
ITEM.description = "Various valuables belonging to a random person."
ITEM.model = "models/kek1ch/jar.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "450"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05