ITEM.name = "Artifact Research Documents (simple)"
ITEM.description = "Describes different artifacts. Covers only the most common artifacts."
ITEM.model = "models/kek1ch/notes_letter_3.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "2250"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05