ITEM.name = "Military maps"
ITEM.description = "Used by military to traverse the zone. Useless, if you have a PDA."
ITEM.model = "models/kek1ch/mili_maps.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "1250"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05