ITEM.name = "Trader's Journal"
ITEM.description = "Contains a list of various deals done by an unknown trader."
ITEM.model = "models/kek1ch/notes_document_case_3.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "1250"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05