ITEM.name = "Anomaly Research Documents (extensive)"
ITEM.description = "Describes different anomalies. Covers all known anomalies."
ITEM.model = "models/kek1ch/notes_writing_book_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "3550"
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.weight = 0.05