--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/bow_deerhunter.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_DeerHunter.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/bow_deerhunter/bow_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.PullBack",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = {
		")weapons/firearms/bow_deerhunter/bow_pullback_01.wav",
		")weapons/firearms/bow_deerhunter/bow_pullback_02.wav",
		")weapons/firearms/bow_deerhunter/bow_pullback_03.wav",
		")weapons/firearms/bow_deerhunter/bow_pullback_04.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.ArrowFly",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/bow_deerhunter/arrow_fly_loop_01.wav",
} )

sound.Add( {
	name = "Weapon_DeerHunter.ArrowFetch",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = {
		")weapons/firearms/bow_deerhunter/arrow_fetch_01.wav",
		")weapons/firearms/bow_deerhunter/arrow_fetch_02.wav",
		")weapons/firearms/bow_deerhunter/arrow_fetch_03.wav",
		")weapons/firearms/bow_deerhunter/arrow_fetch_04.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.ArrowLoad",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_NORM,
	sound = {
		")weapons/firearms/bow_deerhunter/arrow_load_01.wav",
		")weapons/firearms/bow_deerhunter/arrow_load_02.wav",
		")weapons/firearms/bow_deerhunter/arrow_load_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_DeerHunter.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/exp_grenade.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Frag.Toss",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_75dB,
	sound = ")weapons/firearms/exp_frag/Frag_Toss.wav",
} )

sound.Add( {
	name = "Weapon_Frag.Throw",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_75dB,
	sound = ")weapons/firearms/exp_frag/frag_draw.wav",
} )

sound.Add( {
	name = "Weapon_Frag.Draw",
	channel = CHAN_BODY,
	volume = 0.9,
	level = SNDLVL_40dB,
	pitch = {95,105},
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Frag.PinPull",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/exp_frag/Frag_Pull_Pin1.wav",
		")weapons/firearms/exp_frag/Frag_Pull_Pin2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Frag.Explode",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_180dB,
	sound = {
		"^weapons/firearms/exp_frag/Frag_Explode1.wav",
		"^weapons/firearms/exp_frag/Frag_Explode2.wav",
		"^weapons/firearms/exp_frag/Frag_Explode3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Frag.Debris",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_75dB,
	sound = {
		"^weapons/firearms/exp_frag/Frag_Debris1.wav",
		"^weapons/firearms/exp_frag/Frag_Debris2.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/exp_molotov.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Molotov.Ignite_Rag",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_molotov/molotov_rag_ignite_01.wav",
} )

sound.Add( {
	name = "Weapon_Molotov.Rag_Loop",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_molotov/molotov_rag_fire_loop_01.wav",
} )

sound.Add( {
	name = "Weapon_Molotov.Explode",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_molotov/molotov_explode_01.wav",
} )

sound.Add( {
	name = "Weapon_Molotov.Fire_Loop",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_molotov/molotov_fire_loop_01.wav",
} )

sound.Add( {
	name = "Weapon_Molotov.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Molotov.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Molotov.Shove",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_105dB,
	pitch = {95,100},
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/exp_tnt.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_TNT.Explode",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_180dB,
	sound = ")weapons/firearms/exp_tnt/tnt_explode_01.wav",
} )
sound.Add( {
	name = "Weapon_TNT.Explode2",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_180dB,
	sound = ")weapons/firearms/exp_tnt/tnt_explode_02.wav",
} )

sound.Add( {
	name = "Weapon_TNT.Ignite",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_tnt/tnt_ignite_01.wav",
} )

sound.Add( {
	name = "Weapon_TNT.Pop",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_tnt/tnt_pop_01.wav",
} )

sound.Add( {
	name = "Weapon_TNT.Spark_Loop",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_tnt/tnt_spark_loop_01.wav",
} )

sound.Add( {
	name = "Weapon_TNT.Spark_Loop2",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/firearms/exp_tnt/tnt_spark_loop_02.wav",
} )

sound.Add( {
	name = "Weapon_TNT.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_TNT.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_TNT.Shove",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_105dB,
	pitch = {95,100},
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_1022.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_22Pistol.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/rifle_ruger1022/ruger_fire_01.wav",
		")weapons/firearms/rifle_ruger1022/ruger_fire_02.wav"
 	},
} )

sound.Add( {
	name = "Weapon_22Pistol.ClipIn",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_ruger1022/Ruger_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_22Pistol.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_ruger1022/Ruger_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_22Pistol.Empty",
	channel = CHAN_ITEM,
	volume = 1,
	level = SNDLVL_60dB,
	sound = {
		")weapons/firearms/rifle_ruger1022/Ruger_DryFire1.wav",
		")weapons/firearms/rifle_ruger1022/Ruger_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_22Pistol.Slide",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/rifle_ruger1022/Ruger_Slide1.wav",
		")weapons/firearms/rifle_ruger1022/Ruger_Slide3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_22Pistol.SlideLock",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/rifle_ruger1022/Ruger_SlideLock.wav"
 	},
} )

sound.Add( {
	name = "Weapon_22Pistol.DryFire",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/rifle_ruger1022/Ruger_DryFire1.wav",
		")weapons/firearms/rifle_ruger1022/Ruger_DryFire1.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_1911.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_1911.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {98,102},
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_Fire1.wav"
 	},
} )

sound.Add( {
	name = "Weapon_1911.Empty",
	channel = CHAN_AUTO,
	volume = 0.7,
	level = SNDLVL_45dB,
	pitch = {92,100},
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_DryFire.wav"
 	},
} )

sound.Add( {
	name = "Weapon_1911.clipin",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_colt1911/Colt_1911_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_1911.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_colt1911/Colt_1911_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_1911.Empty",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_60dB,
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_Empty.wav",
		")weapons/firearms/hndg_colt1911/Colt_1911_Empty2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_1911.SlideBack",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideBack1.wav",
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideBack2.wav",
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideBack3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_1911.SlideForward",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideForward1.wav",
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideForward2.wav",
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideForward3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_1911.SlideLock",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/hndg_colt1911/Colt_1911_SlideLock.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_500a.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_500Pump.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/shtg_mossberg500/m500_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_500Pump.DryFire",
	channel = CHAN_AUTO,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_mossberg500/M500_DryFire1.wav",
		")weapons/firearms/shtg_mossberg500/M500_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_500Pump.PumpBack",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_mossberg500/M500_PumpBack1.wav",
		")weapons/firearms/shtg_mossberg500/M500_PumpBack2.wav",
		")weapons/firearms/shtg_mossberg500/M500_PumpBack3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_500Pump.PumpForward",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_mossberg500/M500_PumpForward1.wav",
		")weapons/firearms/shtg_mossberg500/M500_PumpForward2.wav",
		")weapons/firearms/shtg_mossberg500/M500_PumpForward3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_500Pump.LoadShell",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_mossberg500/M500_LoadShell1.wav",
		")weapons/firearms/shtg_mossberg500/M500_LoadShell2.wav",
		")weapons/firearms/shtg_mossberg500/M500_LoadShell3.wav",
		")weapons/firearms/shtg_mossberg500/M500_LoadShell4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_500Pump.LoadShell_Special",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_mossberg500/M500_LoadShell3.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_870.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_ShotgunPump.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/shtg_remington870/remington_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunPump.DryFire",
	channel = CHAN_AUTO,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_remington870/Shotgun_Pump_DryFire1.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunPump.PumpBack",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Back1.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Back2.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Back3.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Back4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunPump.PumpForward",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Forward1.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Forward2.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Forward3.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_Forward4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunPump.LoadShell",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell1.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell2.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell3.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell4.wav",
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell5.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunPump.LoadShell_Special",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_remington870/Shotgun_Pump_LoadShell3.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_cz858.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_cz858.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/rifle_cz858/cz858_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_cz858.ClipIn",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_cz858/cz858_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_cz858.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_cz858/cz858_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_cz858.Empty",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_60dB,
	sound = {
		")weapons/firearms/rifle_cz858/Empty.wav",
		")weapons/firearms/rifle_cz858/Empty2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_cz858.Slide",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_cz858/cz858_Slide1.wav",
} )

sound.Add( {
	name = "Weapon_cz858.SlideBack",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_cz858/cz858_SlideBack.wav",
} )

sound.Add( {
	name = "Weapon_cz858.SlideForward",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_cz858/cz858_SlideForward.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_fnfal.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_FAL.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/rifle_fnfal/fnfal_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_FAL.MagIn",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_fnfal/fnfal_magin_01.wav",
} )

sound.Add( {
	name = "Weapon_FAL.MagOut",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_fnfal/fnfal_magout_01.wav",
} )

sound.Add( {
	name = "Weapon_FAL.Boltback",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_fnfal/fnfal_boltback_01.wav",
} )

sound.Add( {
	name = "Weapon_FAL.Boltforward",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_fnfal/fnfal_boltforward_01.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_glock17.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Glock17.Fire1",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_glock17/glock_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Glock17.MagazineIn",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_MagazineIn.wav",
} )

sound.Add( {
	name = "Weapon_glock17.MagazineOut",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_MagazineOut.wav",
} )

sound.Add( {
	name = "Weapon_glock17.DryFire",
	channel = CHAN_AUTO,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_DryFire.wav",
} )

sound.Add( {
	name = "Weapon_glock17.GenericFoley",
	channel = CHAN_ITEM,
	volume = 0.3,
	level = SNDLVL_30dB,
	sound = {
		")weapons/firearms/hndg_glock17/glock17_genericfoley1.wav",
		")weapons/firearms/hndg_glock17/glock17_genericfoley2.wav",
		")weapons/firearms/hndg_glock17/glock17_genericfoley3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_glock17.SlidePull",
	channel = CHAN_ITEM,
	volume = 0.2,0.4,
	pitch = {95,105},
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_SlidePull.wav",
} )

sound.Add( {
	name = "Weapon_glock17.SlideLock",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_SlideLock.wav",
} )

sound.Add( {
	name = "Weapon_glock17.SlideRelease",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_glock17/glock17_SlideRelease.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_jae700.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_JAE700.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_140dB,
	sound = {
		")weapons/firearms/rifle_jae700/jae_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_JAE700.BoltSlide",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_jae700/jae_boltpull_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_JAE700.BoltSlideSlow",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_jae700/jae_boltpull_slow_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_JAE700.Magout",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_jae700/jae_magout_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_JAE700.Magin",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_jae700/jae_magin_01.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_m16a4.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_AR15.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/mil_m16a4/m16_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_AR15.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_AR15.ClipIn",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_AR15.SlideRelease",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_SlideRelease.wav",
} )

sound.Add( {
	name = "Weapon_AR15.Empty",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_DryFire.wav",
} )

sound.Add( {
	name = "Weapon_AR15.Slide",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_Slide.wav",
} )

sound.Add( {
	name = "Weapon_AR15.Slide2",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_Slide2.wav",
} )

sound.Add( {
	name = "Weapon_AR15.DryFire",
	channel = CHAN_ITEM,
	volume = 0.5,
	pitch = PITCH_NORM,
	sound = ")weapons/firearms/mil_m16a4/M16_DryFire.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_m92fs.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Beretta.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_beretta92fs/Beretta92_Fire1.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Beretta.ClipIn",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_Beretta.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_Beretta.DryFire",
	channel = CHAN_AUTO,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_DryFire.wav",
} )

sound.Add( {
	name = "Weapon_Beretta.GenericFoley",
	channel = CHAN_ITEM,
	volume = 0.3,
	level = SNDLVL_30dB,
	sound = {
		")player/clothes_generic_foley_01.wav",
		")player/clothes_generic_foley_02.wav",
		")player/clothes_generic_foley_03.wav",
		")player/clothes_generic_foley_04.wav",
		")player/clothes_generic_foley_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Beretta.Slide",
	channel = CHAN_ITEM,
	volume = 0.2,0.4,
	pitch = {95,105},
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_Slide.wav",
} )

sound.Add( {
	name = "Weapon_Beretta.SlideLock",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_SlideLock.wav",
} )

sound.Add( {
	name = "Weapon_Beretta.SlideRelease",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_SlideRelease.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_mac10.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_MAC10.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/smg_mac10/mac10_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_MAC10.dry",
	channel = CHAN_WEAPON,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/smg_mac10/Mac10_dry01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_MAC10.ClipOut",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/smg_mac10/Mac10_Mag_Out.wav",
} )

sound.Add( {
	name = "Weapon_MAC10.ClipIn",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/smg_mac10/Mac10_Mag_In_1.wav",
} )

sound.Add( {
	name = "Weapon_MAC10.Cliphit",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/smg_mac10/Mac10_Mag_In_2.wav",
} )

sound.Add( {
	name = "Weapon_MAC10.Boltpull",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/smg_mac10/Mac10_Mag_In_3.wav",
} )

sound.Add( {
	name = "Weapon_MAC10.Stockpull",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/smg_mac10/Mac10_Pull.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_mkiii.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Mkiii.Fire",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = ")weapons/firearms/hndg_mkiii/mkiii_fire_01.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.ClipIn",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.ClipOut",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.DryFire",
	channel = CHAN_AUTO,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_mkiii/mkiii_dryfire_01.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.GenericFoley",
	channel = CHAN_ITEM,
	volume = 0.3,
	level = SNDLVL_30dB,
	sound = {
		")player/clothes_generic_foley_01.wav",
		")player/clothes_generic_foley_02.wav",
		")player/clothes_generic_foley_03.wav",
		")player/clothes_generic_foley_04.wav",
		")player/clothes_generic_foley_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Mkiii.Slide",
	channel = CHAN_ITEM,
	volume = 0.2,0.4,
	pitch = {95,105},
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_Slide.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.SlideLock",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_SlideLock.wav",
} )

sound.Add( {
	name = "Weapon_Mkiii.SlideRelease",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/hndg_beretta92fs/Beretta92_SlideRelease.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_mp5a4.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_MP5.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/mil_mp5a4/mp5_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_MP5.Burst",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_140dB,
	pitch = {95, 100},
	sound = ")weapons/firearms/mil_mp5a4/MP5_FireBurst.wav",
} )

sound.Add( {
	name = "Weapon_MP5.dry",
	channel = CHAN_WEAPON,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/mil_mp5a4/MP5_DryFire.wav"
 	},
} )

sound.Add( {
	name = "Weapon_MP5.ClipOut",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/mil_mp5a4/MP5_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_MP5.ClipIn",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/mil_mp5a4/MP5_ClipIn.wav",
} )

sound.Add( {
	name = "Weapon_MP5.SlideLock",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/mil_mp5a4/MP5_SlideLock.wav",
} )

sound.Add( {
	name = "Weapon_MP5.SlideForward",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/mil_mp5a4/MP5_SlideForward.wav",
} )

sound.Add( {
	name = "Weapon_MP5.Slide",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/mil_mp5a4/MP5_Slide.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_sako85.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Sako.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_140dB,
	sound = {
		")weapons/firearms/rifle_sako85/sako_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sako.BoltOpen",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_sako85/Sako_BoltOpen.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sako.BoltClosed",
	channel = CHAN_ITEM,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_sako85/Sako_BoltClosed.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sako.Magout",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_sako85/Sako_magOut.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sako.Magin",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/rifle_sako85/Sako_magIn.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_sks.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_SKS.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/rifle_sks/sks_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_SKS.ClipIn1",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_ClipIn1.wav",
} )

sound.Add( {
	name = "Weapon_SKS.ClipIn2",
	channel = CHAN_ITEM,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_ClipIn2.wav",
} )

sound.Add( {
	name = "Weapon_SKS.ClipOut",
	channel = CHAN_WEAPON,
	volume = 0.9,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_ClipOut.wav",
} )

sound.Add( {
	name = "Weapon_SKS.Empty",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_60dB,
	sound = {
		")weapons/firearms/rifle_sks/Empty.wav",
		")weapons/firearms/rifle_sks/Empty2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_SKS.Slide",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_Slide1.wav",
} )

sound.Add( {
	name = "Weapon_SKS.SlideBack",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_SlideBack.wav",
} )

sound.Add( {
	name = "Weapon_SKS.SlideForward",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_sks/SKS_SlideForward.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_superx3.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_ShotgunAuto.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/shtg_winchestersx3/winchestersx3_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunAuto.SlideBack",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_45dB,
	sound = ")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Slide1.wav",
} )

sound.Add( {
	name = "Weapon_ShotgunAuto.SlideForward",
	channel = CHAN_WEAPON,
	volume = 0.6,
	level = SNDLVL_45dB,
	sound = ")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Slide2.wav",
} )

sound.Add( {
	name = "Weapon_ShotgunAuto.LoadShell",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Reload1.wav",
		")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Reload2.wav",
		")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Reload3.wav",
		")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Reload4.wav",
		")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_Reload5.wav"
 	},
} )

sound.Add( {
	name = "Weapon_ShotgunAuto.DryFire",
	channel = CHAN_AUTO,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/shtg_winchestersx3/Shotgun_SemiAuto_DryFire.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_sv10.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "weapon_db.shellout",
	channel = CHAN_WEAPON,
	volume = 0.85,
	level = SNDLVL_120dB,
	sound = {
		")weapons/firearms/ShellCasing_1Shotty1.wav",
		")weapons/firearms/ShellCasing_1Shotty2.wav",
		")weapons/firearms/ShellCasing_1Shotty3.wav",
		")weapons/firearms/ShellCasing_1Shotty4.wav"
 	},
} )

sound.Add( {
	name = "weapon_db.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,105},
	sound = {
		")weapons/firearms/shtg_berettasv10/beretta_fire_01.wav"
 	},
} )

sound.Add( {
	name = "weapon_db.Close",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_Close.wav",
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_Close2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_SV10.Open",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_Open.wav",
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_Open2.wav"
 	},
} )

sound.Add( {
	name = "weapon_db.DryFire",
	channel = CHAN_AUTO,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_DryFire1.wav",
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "weapon_db.GenericFoley",
	channel = CHAN_ITEM,
	volume = 0.3,
	level = SNDLVL_55dB,
	sound = {
		")player/clothes_generic_foley_01.wav",
		")player/clothes_generic_foley_02.wav",
		")player/clothes_generic_foley_03.wav",
		")player/clothes_generic_foley_04.wav",
		")player/clothes_generic_foley_05.wav"
 	},
} )

sound.Add( {
	name = "weapon_db.LoadShell",
	channel = CHAN_ITEM,
	volume = 0.2,0.4,
	pitch = {95,105},
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_LoadShell1.wav",
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_LoadShell2.wav",
		")weapons/firearms/shtg_berettasv10/Shotgun_DoubleBarrel_LoadShell3.wav",
		")weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_LoadShell4.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_sw686.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_686.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_sw686/revolver_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.Dry",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_70dB,
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_DryFire1.wav",
		")weapons/firearms/hndg_sw686/Revolver_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.ChamberClick",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_Load_1.wav",
		")weapons/firearms/hndg_sw686/Revolver_Load_2.wav",
		")weapons/firearms/hndg_sw686/Revolver_Load_3.wav",
		")weapons/firearms/hndg_sw686/Revolver_Load_4.wav",
		")weapons/firearms/hndg_sw686/Revolver_Load_5.wav",
		")weapons/firearms/hndg_sw686/Revolver_Load_6.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.CycleSpin",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_45dB,
	sound = ")weapons/firearms/hndg_sw686/Revolver_SpinCyl.wav",
} )

sound.Add( {
	name = "Weapon_686.HammerBack",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_HammerBack1.wav",
		")weapons/firearms/hndg_sw686/Revolver_HammerBack2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.Load_3",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_Load_3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.Load_2",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_Load_2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.Load_5",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_Load_5.wav"
 	},
} )

sound.Add( {
	name = "Weapon_686.Load_6",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = {
		")weapons/firearms/hndg_sw686/Revolver_Load_6.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/fa_winchester1892.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Win1892.Single",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = {
		")weapons/firearms/rifle_win1892/win1892_fire_01.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Win1892.DryFire",
	channel = CHAN_AUTO,
	volume = 0.6,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/rifle_win1892/Win1892_DryFire1.wav",
		")weapons/firearms/rifle_win1892/Win1892_DryFire2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Win1892.LeverDown",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_win1892/Win1892_Leverdown2.wav",
} )

sound.Add( {
	name = "Weapon_Win1892.LeverUp",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_55dB,
	sound = ")weapons/firearms/rifle_win1892/Win1892_Leverup2.wav",
} )

sound.Add( {
	name = "Weapon_Win1892.LoadShell",
	channel = CHAN_ITEM,
	volume = 0.4,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/rifle_win1892/Win1892_LoadShell1.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell2.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell3.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Win1892.LoadShell_Special",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	sound = {
		")weapons/firearms/rifle_win1892/Win1892_LoadShell1.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell2.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell3.wav",
		")weapons/firearms/rifle_win1892/Win1892_LoadShell4.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_abrasivesaw.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_AbrasiveSaw.IdleLoop",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_105,
	sound = ")weapons/melee/circular_saw/circular_saw_idle_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.SawLoop",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_135dB,
	sound = ")weapons/melee/circular_saw/circular_saw_fast_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.IdleToSaw",
	channel = CHAN_AUTO,
	volume = 0.4,
	level = SNDLVL_95dB,
	sound = ")weapons/melee/circular_saw/circular_saw_idle_to_fast_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.SawToIdle",
	channel = CHAN_AUTO,
	volume = 0.4,
	level = SNDLVL_95dB,
	sound = ")weapons/melee/circular_saw/circular_saw_fast_to_idle_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.Off",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/circular_saw/circular_saw_shut_off_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.StartupFailed",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/circular_saw/circular_saw_start_fail_01.wav",
} )

sound.Add( {
	name = "Weapon_AbrasiveSaw.StartupSuccess",
	channel = CHAN_NORM,
	volume = 0.7,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/circular_saw/circular_saw_start_success_01.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_axe_fire.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Fireaxe.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fireaxe.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fireaxe.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.FireaxeLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.FireaxeHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_bat_metal.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Bat.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Bat.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Bat.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.BatLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.BatHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_chainsaw.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Chainsaw.IdleLoop",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_105,
	sound = ")weapons/melee/chainsaw/Chainsaw_idleloop.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.SawLoop",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_135dB,
	sound = ")weapons/melee/chainsaw/Chainsaw_sawloop.wav",
} )
	
sound.Add( {
	name = "Weapon_Chainsaw.IdleLoop2",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_105,
	sound = ")weapons/melee/chainsaw/Chainsaw_idleloop2.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.SawLoop2",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_135dB,
	sound = ")weapons/melee/chainsaw/Chainsaw_sawloop2.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.IdleToSaw",
	channel = CHAN_AUTO,
	volume = 0.4,
	level = SNDLVL_95dB,
	sound = ")weapons/melee/chainsaw/Chainsaw_idletosaw.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.SawToIdle",
	channel = CHAN_AUTO,
	volume = 0.4,
	level = SNDLVL_95dB,
	sound = ")weapons/melee/chainsaw/Chainsaw_sawtoidle.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.Off",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/chainsaw/Chainsaw_turnoff.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.StartupFailed",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/chainsaw/Chainsaw_failedstart.wav",
} )

sound.Add( {
	name = "Weapon_Chainsaw.StartupSuccess",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_NORM,
	sound = ")weapons/melee/chainsaw/Chainsaw_successstart.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_crowbar.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Crowbar.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Crowbar.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Crowbar.Shove",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_105dB,
	pitch = {95,100},
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.CrowbarLight",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_105dB,
	pitch = {95,100},
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.CrowbarHeavy",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_105dB,
	pitch = {98,102},
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_etool.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Etool.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.SwingLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.SwingHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.Spin",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/etool/etool_spin_01.wav",
		")weapons/melee/etool/etool_spin_02.wav",
		")weapons/melee/etool/etool_spin_03.wav",
		")weapons/melee/etool/etool_spin_04.wav",
		")weapons/melee/etool/etool_spin_05.wav",
		")weapons/melee/etool/etool_spin_06.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Etool.AdjustStraight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = ")weapons/melee/etool/etool_to_default_01.wav",
} )

sound.Add( {
	name = "Weapon_Etool.AdjustAlternate",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = ")weapons/melee/etool/etool_to_alternate_01.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_fists.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Fist.Draw",
	channel = CHAN_AUTO,
	level = SNDLVL_NORM,
	volume = 0.6,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fist.Holster",
	channel = CHAN_AUTO,
	level = SNDLVL_NORM,
	volume = 0.6,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Crowbar.Single",
	channel = CHAN_WEAPON,
	level = SNDLVL_NORM,
	volume = 0.5,
	sound = {
		")weapons/melee/swing_fists_01.wav",
		")weapons/melee/swing_fists_02.wav",
		")weapons/melee/swing_fists_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fist.HitFlesh",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.8,
	pitch = {94, 108},
	sound = {
		")weapons/melee/fists/Fist_Hit1.wav",
		")weapons/melee/fists/Fist_Hit2.wav",
		")weapons/melee/fists/Fist_Hit3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fist.HitWorld",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.7,
	pitch = {80, 90},
	sound = {
		")weapons/melee/fists/Fist_Hit1.wav",
		")weapons/melee/fists/Fist_Hit2.wav",
		")weapons/melee/fists/Fist_Hit3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Fist.Shove",
	channel = CHAN_WEAPON,
	level = SNDLVL_64dB,
	volume = 1.0,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_hatchet.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Hatchet.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hatchet.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hatchet.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.HatchetLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.HatchetHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_kitknife.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_KitKnife.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.5,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_KitKnife.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.5,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_KitKnife.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.5,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_KitKnife.SwingLight",
	channel = CHAN_WEAPON,
	volume = 1,
	level = SNDLVL_NORM,
	pitch = PITCH_NORM,
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_KitKnife.SwingHeavy",
	channel = CHAN_WEAPON,
	volume = 1,
	level = SNDLVL_NORM,
	pitch = PITCH_NORM,
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_machete.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Machete.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Machete.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Machete.Shove",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_NORM,
	pitch = {95,100},
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.MacheteLight",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_NORM,
	pitch = {95,100},
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.MacheteHeavy",
	channel = CHAN_WEAPON,
	volume = 0.55,
	level = SNDLVL_NORM,
	pitch = {95,100},
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Machete.Melee_Hit",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_NORM,
	pitch = {98,102},
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Machete.Melee_HitWorld",
	channel = CHAN_WEAPON,
	volume = 0.7,
	level = SNDLVL_90dB,
	pitch = {90,120},
	sound = {
		")weapons/crowbar/crowbar_impact1.wav",
		")weapons/crowbar/crowbar_impact2.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_pipe_lead.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_PipeLead.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_PipeLead.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_PipeLead.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.PipeLeadLight",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_75dB,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.PipeLeadHeavy",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_75dB,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_shovel.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Spade.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Spade.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Spade.Shove",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.SpadeLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.SpadeHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_heavy_sharp_01.wav",
		")weapons/melee/swing_heavy_sharp_02.wav",
		")weapons/melee/swing_heavy_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_sledge.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Sledge.Draw",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {98,100},
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sledge.Holster",
	channel = CHAN_WEAPON,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {98,100},
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sledge.Swing",
	channel = CHAN_WEAPON,
	level = SNDLVL_85dB,
	volume = 1.0,
	pitch = {95,100},
	sound = {
		")weapons/melee/swing_heavy_blunt_01.wav",
		")weapons/melee/swing_heavy_blunt_02.wav",
		")weapons/melee/swing_heavy_blunt_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sledge.Shove",
	channel = CHAN_WEAPON,
	level = SNDLVL_85dB,
	volume = 1.0,
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sledge.HitFlesh",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/sledge/sledge_hit1.wav",
		")weapons/melee/sledge/sledge_hit2.wav",
		")weapons/melee/sledge/sledge_hit3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Sledge.HitWorld",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/bat/Woodbat_hitworld1.wav",
		")weapons/bat/Woodbat_hitworld2.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/me_wrench.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Wrench.Draw",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {98,100},
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Wrench.Holster",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {98,100},
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Wrench.Shove",
	channel = CHAN_ITEM,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {98,100},
	sound = {
		")player/shove_01.wav",
		")player/shove_02.wav",
		")player/shove_03.wav",
		")player/shove_04.wav",
		")player/shove_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.Wrench",
	channel = CHAN_WEAPON,
	level = SNDLVL_85dB,
	volume = 0.85,
	pitch = {98,100},
	sound = {
		")weapons/melee/swing_light_sharp_01.wav",
		")weapons/melee/swing_light_sharp_02.wav",
		")weapons/melee/swing_light_sharp_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_barricade.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Hammer.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.BoardDraw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/board-draw1.wav",
		")weapons/melee/hammer/board-draw2.wav",
		")weapons/melee/hammer/board-draw3.wav",
		")weapons/melee/hammer/board-draw4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.BoardHolster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/board-holster1.wav",
		")weapons/melee/hammer/board-holster2.wav",
		")weapons/melee/hammer/board-holster3.wav",
		")weapons/melee/hammer/board-holster4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.Barricade",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/barricade-1.wav",
		")weapons/melee/hammer/barricade-2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.BoardLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/board_damage-light1.wav",
		")weapons/melee/hammer/board_damage-light2.wav",
		")weapons/melee/hammer/board_damage-light3.wav",
		")weapons/melee/hammer/board_damage-light4.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.BoardHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/board_damage-heavy1.wav",
		")weapons/melee/hammer/board_damage-heavy2.wav",
		")weapons/melee/hammer/board_damage-heavy3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Hammer.BoardBroken",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")weapons/melee/hammer/board_damage-broken1.wav",
		")weapons/melee/hammer/board_damage-broken2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.HammerLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/hammer/Hammer_Hit1.wav",
		")weapons/melee/hammer/Hammer_Hit2.wav",
		")weapons/melee/hammer/Hammer_Hit3.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.HammerSwing",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_extinguisher.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Extinguisher.Extinguish",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_105dB,
	sound = ")weapons/tools/fire_extinguisher/Fire_Extinguisger_StartLoop.wav",
} )

sound.Add( {
	name = "Weapon_Extinguisher.Extinguish_Stop",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_105dB,
	sound = ")weapons/tools/fire_extinguisher/Fire_Extinguisger_Stop.wav",
} )

sound.Add( {
	name = "Weapon_Extinguisher.Lever",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_105dB,
	sound = ")weapons/tools/fire_extinguisher/Fire_Extinguisger_Lever.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_flare_gun.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "FlareGun.BarrelOpen",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_BarrelOpen.wav",
} )

sound.Add( {
	name = "FlareGun.BarrelClose",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_BarrelClosed.wav",
} )

sound.Add( {
	name = "FlareGun.Fire",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_GUNFIRE,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_Fire.wav",
} )

sound.Add( {
	name = "FlareGun.HammerDown",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_HammerDown.wav",
} )

sound.Add( {
	name = "FlareGun.HammerUp",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_HammerUp.wav",
} )

sound.Add( {
	name = "FlareGun.Load",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_Load.wav",
} )

sound.Add( {
	name = "FlareGun.SpentOut",
	channel = CHAN_ITEM,
	volume = 1.0,
	level = SNDLVL_45dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flaregun_SpentOut.wav",
} )

sound.Add( {
	name = "FlareGun.Pop",
	channel = CHAN_WEAPON,
	volume = 1.0,
	level = SNDLVL_90dB,
	pitch = {95,100},
	sound = ")weapons/tools/flaregun/Flare_Pop.wav",
} )

sound.Add( {
	name = "Flare.Screech",
	channel = CHAN_VOICE,
	volume = 1,
	pitch = 100,
	level = 120,
	sound = ")weapons/tools/flaregun/flare_whistle.wav",
} )

sound.Add( {
	name = "Flare.Touch",
	channel = CHAN_VOICE,
	volume = 1,
	pitch = 100,
	level = 120,
	sound = ")weapons/tools/flaregun/flare_pop.wav",
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_maglite.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Flashlight.On",
	channel = CHAN_BODY,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {97,98},
	sound = {
		")weapons/tools/flashlight/flashlight_on1.wav",
		")weapons/tools/flashlight/flashlight_on2.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Flashlight.Off",
	channel = CHAN_BODY,
	volume = 0.5,
	level = SNDLVL_55dB,
	pitch = {97,98},
	sound = {
		")weapons/tools/flashlight/flashlight_off1.wav",
		")weapons/tools/flashlight/flashlight_off2.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_welder.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Welder.Flame",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_90dB,
	sound = ")weapons/tools/welder/Welder_Loop.wav",
} )
sound.Add( {
	name = "Weapon_Welder.Flame2",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_90dB,
	sound = ")weapons/tools/welder/Welder_Loop2.wav",
} )

sound.Add( {
	name = "Weapon_Welder.Draw",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_draw_01.wav",
		")player/weapon_draw_02.wav",
		")player/weapon_draw_03.wav",
		")player/weapon_draw_04.wav",
		")player/weapon_draw_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Welder.Holster",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 0.4,
	sound = {
		")player/weapon_holster_01.wav",
		")player/weapon_holster_02.wav",
		")player/weapon_holster_03.wav",
		")player/weapon_holster_04.wav",
		")player/weapon_holster_05.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.WelderLight",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Melee.WelderHeavy",
	channel = CHAN_ITEM,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/melee/swing_light_blunt_01.wav",
		")weapons/melee/swing_light_blunt_02.wav",
		")weapons/melee/swing_light_blunt_03.wav"
 	},
} )
--Generated by TFA's Sound Autoconversion Script
--Original Path: D:/SteamGames/steamapps/common/nmrih/nmrih/scripts/weapons_soundscripts/tool_zippo.txt
SNDLVL_GUNFIRE = 120
SNDLVL_NORM = 80
SNDLVL_20dB = 20
SNDLVL_25dB = 25
SNDLVL_30dB = 30
SNDLVL_35dB = 35
SNDLVL_40dB = 40
SNDLVL_45dB = 45
SNDLVL_50dB = 50
SNDLVL_55dB = 55
SNDLVL_60dB = 60
SNDLVL_65dB = 65
SNDLVL_70dB = 70
SNDLVL_75dB = 75
SNDLVL_80dB = 80
SNDLVL_85dB = 85
SNDLVL_90dB = 90
SNDLVL_95dB = 95
SNDLVL_100dB = 100
SNDLVL_105dB = 105
SNDLVL_105 = 105
SNDLVL_110dB = 110
SNDLVL_115dB = 115
SNDLVL_120dB = 120
SNDLVL_125dB = 125
SNDLVL_130dB = 130
SNDLVL_135dB = 135
SNDLVL_140dB = 140
SNDLVL_145dB = 145
SNDLVL_150dB = 150
SNDLVL_155dB = 155
SNDLVL_160dB = 160
SNDLVL_165dB = 165
SNDLVL_170dB = 170
SNDLVL_175dB = 175
SNDLVL_180dB = 180
	
sound.Add( {
	name = "Weapon_Zippo.Open",
	channel = CHAN_AUTO,
	volume = 1.0,
	level = SNDLVL_NORM,
	sound = {
		")weapons/tools/zippo/zippo_open_01.wav",
		")weapons/tools/zippo/zippo_open_02.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Zippo.Close",
	channel = CHAN_AUTO,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/tools/zippo/zippo_close_01.wav",
		")weapons/tools/zippo/zippo_close_02.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Zippo.Strike_Fail",
	channel = CHAN_AUTO,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = {
		")weapons/tools/zippo/zippo_strike_fail_01.wav",
		")weapons/tools/zippo/zippo_strike_fail_02.wav",
		")weapons/tools/zippo/zippo_strike_fail_03.wav"
 	},
} )

sound.Add( {
	name = "Weapon_Strike_Success",
	channel = CHAN_AUTO,
	level = SNDLVL_NORM,
	volume = 1.0,
	sound = ")weapons/tools/zippo/zippo_strike_success_01.wav",
} )
