CustomizableWeaponry:addFireSound("CW_KK_INS2_M16A4_FIRE", "weapons/m16a4/m16a4_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M16A4_FIRE_SUPPRESSED", "weapons/m16a4/m16a4_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_BOLTBACK", "weapons/m16a4/handling/m16_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_BOLTRELEASE", "weapons/m16a4/handling/m16_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_EMPTY", "weapons/m16a4/handling/m16_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_FIRESELECT", "weapons/m16a4/handling/m16_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_HIT", "weapons/m16a4/handling/m16_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_MAGHITRELEASE", "weapons/m16a4/handling/m16_maghitrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_MAGIN", "weapons/m16a4/handling/m16_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_MAGOUT", "weapons/m16a4/handling/m16_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M16A4_MAGRELEASE", "weapons/m16a4/handling/m16_magrelease.wav")