CustomizableWeaponry:addFireSound("CW_KK_INS2_M4SPEC_FIRE", "weapons/m4spec/mp5k_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M4SPEC_FIRE_SUPPRESSED", "weapons/m4spec/mp5k_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_BOLTBACK", "weapons/m4spec/handling/mp5k_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_BOLTLOCK", "weapons/m4spec/handling/mp5k_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_BOLTRELEASE", "weapons/m4spec/handling/mp5k_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_EMPTY", "weapons/m4spec/handling/mp5k_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_FIRESELECT", "weapons/m4spec/handling/mp5k_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_MAGIN", "weapons/m4spec/handling/mp5k_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_MAGOUT", "weapons/m4spec/handling/mp5k_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4SPEC_MAGRELEASE", "weapons/m4spec/handling/mp5k_magrelease.wav")