ITEM.name = "Moonlight"
ITEM.model ="models/nasca/etherealsrp_artifacts/moonlight.mdl"
ITEM.description = "Light emits from this artifact."
ITEM.longdesc = "This unique electrostatic artifact can resonate under the influence of psy-waves. Stalkers have learned to fine-tune the artifact so that it resonates in opposite phase to the main source of emissions, thus significantly neutralizing their effects. This orb of considerable beauty also increases electrical protection by reducing conductivity in the body when exposed to high levels of electricity. It also enhances energy and stamina recovery, allowing its user to feel energetic and refreshed. An unwanted side effect is that it decreases healing rate and coagulation. This artifact is also extremely light and very portable. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 36000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.buff = "end"
ITEM.buffval = 10
ITEM.debuff = "rads"
ITEM.debuffval = 15
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = -0.15,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.25,
}