ITEM.name = "Mica"
ITEM.model ="models/nasca/etherealsrp_artifacts/mica.mdl"
ITEM.description = "Brown artifact."
ITEM.longdesc = "A semi-transparent, hard object. A very rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 34500
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.buff = "woundheal"
ITEM.buffval = 40
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = -0.10,
	["Radiation"] = 0.00,
	["Chemical"] = -0.10,
	["Psi"] = 0.00,
}
ITEM.weight = 1