ITEM.name = "Slime"
ITEM.model ="models/nasca/etherealsrp_artifacts/slime.mdl"
ITEM.description = "Slimey."
ITEM.longdesc = "An artifact connected by threads of slime. Common artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2450
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5
ITEM.isArtefact = true
ITEM.buff = "woundheal"
ITEM.buffval = 13
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = -0.10,
	["Radiation"] = 0.00,
	["Chemical"] = -0.10,
	["Psi"] = 0.00,
}