ix.randomitems.tables["cache_artifact_tier1"] = {
  {1000, {"artifact_mementomori"}},
  { 750, {"artifact_blowncap"}},
  {2000, {"artifact_bolt"}},
  { 500, {"artifact_battery"}},
  {1000, {"artifact_droplet"}},
  { 800, {"artifact_bonecluster"}},
  { 600, {"artifact_sparkler"}},
  { 600, {"artifact_slime"}},
  { 200, {"artifact_slug"}},
  {1000, {"artifact_thorn"}},
  { 100, {"artifact_cell"}},
}

ix.randomitems.tables["cache_artifact_tier2"] = {
  {1000, {"artifact_mementomori"}},
  {1000, {"artifact_blowncap"}},
  { 500, {"artifact_capacitor"}},
  { 750, {"artifact_battery"}},
  { 800, {"artifact_mycelia"}},
  { 800, {"artifact_urchin"}},
  {1000, {"artifact_sparkler"}},
  { 600, {"artifact_flash"}},
  { 800, {"artifact_slug"}},
  { 600, {"artifact_eye"}},
  {1000, {"artifact_cell"}},
  {1000, {"artifact_crystal"}},
}

ix.randomitems.tables["cache_artifact_tier3"] = {
  {1000, {"artifact_mica"}},
  { 800, {"artifact_arachno"}},
  { 200, {"artifact_halo"}},
  {1000, {"artifact_mamasbeads"}},
  { 300, {"artifact_gmamasbeads"}},
  {1000, {"artifact_uchin"}},
  { 500, {"artifact_kolobok"}},
  { 600, {"artifact_moonlight"}},
  {1000, {"artifact_slug"}},
  {1000, {"artifact_eye"}},
  { 600, {"artifact_flame"}},
}

-- Extremely high value items, should be used sparingly in stashes
ix.randomitems.tables["cache_valuable"] = {
  {500, {"value_pcpart_fpga"}},
  {500, {"value_pcpart_gpu"}},
  { 300, {"value_techtool_1"}},
  { 200, {"value_techtool_2"}},
  { 100, {"value_techtool_3"}},
  {1500, {"value_goldchain"}},
  { 800, {"value_wirelesstrans"}},
  {2000, {"drug_cocaine"}},
  {2000, {"value_currency_euro", {["quantity"] = 200}}},
  {2000, {"value_currency_dollars", {["quantity"] = 250}}},
  {1500, {"value_currency_euro", {["quantity"] = 400}}},
  {1500, {"value_currency_dollars", {["quantity"] = 500}}},
  {1000, {"value_currency_euro", {["quantity"] = 600}}},
  {1000, {"value_currency_dollars", {["quantity"] = 750}}},
  { 500, {"value_currency_euro", {["quantity"] = 800}}},
  { 500, {"value_currency_dollars", {["quantity"] = 1000}}},
  {  30, {"value_memorymodule"}},
  {  50, {"value_calculationunit"}},
  {  20, {"value_monitoringunit"}},
  {   5, {"value_frequencymodulator"}},
  { 450, {"artifact_galaxy"}},
  {   2, {"artifact_midas"}},
  { 900, {"artifact_panacea"}},
  { 900, {"artifact_gaia"}},
  { 900, {"artifact_halo"}},
  { 900, {"artifact_gmamasbeads"}},
  {1, {"cassette_firelake"}},
  {1, {"cassette_freedom"}},
  {1, {"cassette_standart"}},
  {1, {"cassette_true"}},
}