ix.randomitems.tables["bandit_pistol_drops"] = {
  {250, {"brhp", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 8}}},
  {250, {"lugerp08", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 4}}},
  {250, {"makarov", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 5}}},
  {250, {"cz52", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 6}}},
  {250, {"tokarev", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 6}}},
  {250, {"c96", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 4}}},
}

ix.randomitems.tables["bandit_shotgun_drops"] = {
  {250, {"toz34", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 1}}},
  {250, {"toz66", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 1}}},
  {250, {"toz66short", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 1}}},
  {250, {"toz34short", {["durability"] = 5, ["wear"] = 5, ["ammo"] = 1}}},
}

ix.randomitems.tables["bandit_pistol_loot"] = {
  {50,  {"drink_bottlebeer_1", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_2", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_3", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_4", {["quantity"] = 1}}},
  {25,  {"drink_bottlebeer_5", {["quantity"] = 1}}},
  {25,  {"drink_bottlebeer_6", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_1", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_2", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_3", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_4", {["quantity"] = 1}}},
  {50,  {"drink_canbeer_5", {["quantity"] = 1}}},
  {25,  {"drink_canbeer_6", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_1", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_2", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_3", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_4", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_5", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_6", {["quantity"] = 1}}},
  {30,  {"food_nuts_1"}},
  {30,  {"food_nuts_2"}},
  {30,  {"food_sausage_1"}},
  {30,  {"food_sausage_2"}},
  {30,  {"food_cheese_1"}},
  {30,  {"food_cheese_2"}},
  {30,  {"food_cheese_3"}},
  {15,  {"food_can_beans"}},
  {15,  {"food_can_chilibeans"}},
  {15,  {"food_can_corn"}},
  {15,  {"food_can_olive"}},
  {15,  {"food_can_tomato"}},
  {15,  {"food_can_tuna"}},
  {15,  {"food_can_tushonka"}},
  {15,  {"food_can_sprats"}},
  {25,  {"drink_bottletea"}},
  {50,  {"drink_bottlewater"}},
  {300, {"drink_bottlewaterdirty"}},
  {75,  {"drink_canwater"}},

  {50,  {"9x18", {["quantity"] = 9}}},
  {20,  {"9x18hp", {["quantity"] = 9}}},
  {50,  {"9x19", {["quantity"] = 7}}},
  {20,  {"9x19hp", {["quantity"] = 7}}},
  {50,  {"762x25", {["quantity"] = 7}}},
  {20,  {"762x25hp", {["quantity"] = 7}}},
  {50,  {"45acp", {["quantity"] = 6}}},
}

ix.randomitems.tables["bandit_shotgun_loot"] = {
  {50,  {"drink_bottlebeer_1", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_2", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_3", {["quantity"] = 1}}},
  {50,  {"drink_bottlebeer_4", {["quantity"] = 1}}},
  {25,  {"drink_bottlebeer_5", {["quantity"] = 1}}},
  {25,  {"drink_bottlebeer_6", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_1", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_2", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_3", {["quantity"] = 1}}},
  {75,  {"drink_canbeer_4", {["quantity"] = 1}}},
  {50,  {"drink_canbeer_5", {["quantity"] = 1}}},
  {25,  {"drink_canbeer_6", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_1", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_2", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_3", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_4", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_5", {["quantity"] = 1}}},
  {25,  {"drug_cigarette_6", {["quantity"] = 1}}},
  {30,  {"food_nuts_1"}},
  {30,  {"food_nuts_2"}},
  {30,  {"food_sausage_1"}},
  {30,  {"food_sausage_2"}},
  {30,  {"food_cheese_1"}},
  {30,  {"food_cheese_2"}},
  {30,  {"food_cheese_3"}},
  {15,  {"food_can_beans"}},
  {15,  {"food_can_chilibeans"}},
  {15,  {"food_can_corn"}},
  {15,  {"food_can_olive"}},
  {15,  {"food_can_tomato"}},
  {15,  {"food_can_tuna"}},
  {15,  {"food_can_tushonka"}},
  {15,  {"food_can_sprats"}},
  {25,  {"drink_bottletea"}},
  {50,  {"drink_bottlewater"}},
  {300, {"drink_bottlewaterdirty"}},
  {75,  {"drink_canwater"}},

  {50,  {"12gauge", {["quantity"] = 4}}},
  {50,  {"12gaugesg", {["quantity"] = 4}}},
  {50,  {"45acp41", {["quantity"] = 7}}},
}