CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK_FIRE", "weapons/rpk/rpk_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_RPK_FIRE_SUPPRESSED", "weapons/rpk/rpk_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BIPODDEPLOY", "weapons/rpk/handling/rpk_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BIPODRETRACT", "weapons/rpk/handling/rpk_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BOLTBACK", "weapons/rpk/handling/rpk_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_BOLTRELEASE", "weapons/rpk/handling/rpk_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_DEPLOYGROUNDHIT", "weapons/rpk/handling/rpk_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_EMPTY", "weapons/rpk/handling/rpk_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_ENDDEPLOYEDRELOAD", "weapons/rpk/handling/rpk_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_FETCHMAG", "weapons/rpk/handling/rpk_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_FIRESELECT", "weapons/rpk/handling/rpk_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGIN", "weapons/rpk/handling/rpk_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGOUT", "weapons/rpk/handling/rpk_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGOUTRATTLE", "weapons/rpk/handling/rpk_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_MAGRELEASE", "weapons/rpk/handling/rpk_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_RPK_RATTLE", "weapons/rpk/handling/rpk_rattle.wav")