CustomizableWeaponry:addFireSound("CW_BER_SVT40_FIRE", "weapons/cw_ber_svt40/shot.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_BER_SVT40_FIRE_SUPPRESSED", "weapons/cw_ber_svt40/shots.wav", 1, 100, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_BER_SVT40_MAGOUT", "weapons/cw_ber_svt40/clipout.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_MAGIN", "weapons/cw_ber_svt40/clipin.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_MAGSLAP", "weapons/cw_ber_svt40/slap.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_BOLTPULL", "weapons/cw_ber_svt40/boltpull.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_BOLTBACK", "weapons/cw_ber_svt40/boltback.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_BOLTFORWARD", "weapons/cw_ber_svt40/boltforward.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SVT40_DRAW", "weapons/cw_ber_svt40/draw.wav")