CustomizableWeaponry:addFireSound("CW_KK_INS2_ACR_FIRE", "weapons/acr/mk18_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_ACR_FIRE_SUPPRESSED", "weapons/acr/mk18_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_BOLTBACK", "weapons/acr/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_BOLTRELEASE", "weapons/acr/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_EMPTY", "weapons/acr/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_FIRESELECT", "weapons/acr/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_HIT", "weapons/acr/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_MAGIN", "weapons/acr/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_MAGOUT", "weapons/acr/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_ACR_MAGRELEASE", "weapons/acr/handling/mk18_magrelease.wav")