ITEM.name = "Advanced Locksmith's Kit"
ITEM.description = "An Advanced Locksmith's Kit"
ITEM.longdesc = "Large kit of various tools designated to test advanced security features of industrial locks."
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 5