ITEM.name = "Brute-Force PDA"
ITEM.description = "A Brute-Force PDA"
ITEM.longdesc = "A pair of modern, high performance PDAs with various exploits and software on board. If all else fails, they automatically try to 'guess' the system's password, using combined GPU and CPU power to accomplish it."
ITEM.model = "models/kek1ch/dev_pda.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 5
ITEM.weight = 0.25