ITEM.name = "Decoder"
ITEM.description = "A Decoder"
ITEM.longdesc = "Rare device designed to crack security systems by decoding their keys."
ITEM.model = "models/alyx_emptool_prop.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 50000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 6