ITEM.name = "Electrician's Kit"
ITEM.description = "An Electrician's Kit"
ITEM.longdesc = "A full set of tools and devices to maintain, repair and bypass commercial security systems."
ITEM.model = "models/kek1ch/toolkit_p.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 15000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 4
ITEM.weight = 0.25