ITEM.name = "Live USB"
ITEM.description = "A Live USB"
ITEM.longdesc = "Simple USB stick with software to diagnose and fix computer problems. Or bypass low quality security."
ITEM.model = "models/kek1ch/dev_flash_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 1
ITEM.weight = 0.25