ITEM.name = "Lockpick Gun"
ITEM.description = "A Lockpick Gun"
ITEM.longdesc = "Swiss Lockpick Gun, quickly and efficiently defeats low-level locks, but has no answer to complex designs."
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 2