ITEM.name = "Pulser"
ITEM.description = "A Pulser"
ITEM.longdesc = "Basic tool for electricians to analyze wires and send signals through them, a smart person can use this to bypass electronic locks."
ITEM.model = "models/alyx_emptool_prop.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 2
ITEM.weight = 0.25