ITEM.name = "Security Testing Kit"
ITEM.description = "A Security Testing Kit"
ITEM.longdesc = "Tools designed to help a trained technician to test the security of advanced systems, mostly by bypassing them."
ITEM.model = "models/kek1ch/toolkit_p.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 5
ITEM.weight = 0.25