ITEM.name = "Set of Lockpicks"
ITEM.description = "A Set of Lockpicks"
ITEM.longdesc = "Basic equipment for lockpicking, gives tools to handle most locks in 'field' setting."
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 3
ITEM.weight = 0.25