ITEM.name = "Zero-day USB"
ITEM.description = "A Zero-day USB"
ITEM.longdesc = "A USB stick containing exploits that haven't gone public yet, and thus not patched. Commercial systems do not patch these weaknesses on purpose to allow Intelligence Agencies access."
ITEM.model = "models/kek1ch/dev_flash_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 15000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 4
ITEM.weight = 0.25