CustomizableWeaponry:addFireSound("CW_KK_INS2_MP5K_FIRE", "weapons/mp5k/mp5k_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_MP5K_FIRE_SUPPRESSED", "weapons/mp5k/mp5k_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTBACK", "weapons/mp5k/handling/mp5k_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTLOCK", "weapons/mp5k/handling/mp5k_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_BOLTRELEASE", "weapons/mp5k/handling/mp5k_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_EMPTY", "weapons/mp5k/handling/mp5k_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_FIRESELECT", "weapons/mp5k/handling/mp5k_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGIN", "weapons/mp5k/handling/mp5k_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGOUT", "weapons/mp5k/handling/mp5k_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP5K_MAGRELEASE", "weapons/mp5k/handling/mp5k_magrelease.wav")