ITEM.name = "AK-12u"
ITEM.description = "The AK-12 is a Russian 5.45x39mm assault rifle designed by Kalashnikov Concern. The most modern AK-Pattern rifle, it features various upgrades over the older versions still in use across the world."
ITEM.model = "models/weapons/ethereal/w_ak12u.mdl"
ITEM.class = "cw_kk_ins2_ak12u"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 57350
ITEM.flag = "Z"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 6
ITEM.weight = 3.1
ITEM.repairCost = ITEM.price/100*1