ITEM.name = "M40A1"
ITEM.description = "Each M40 is built from a Remington 700 bolt-action rifle, and is modified by USMC armorers at Marine Corps Base Quantico, using components from a number of suppliers. New M40A5s are being built, and A1s are upgraded to A3s and A5s as they rotate into the armory for service and repair. The rifles have had many sub-variations in telescopic sights, and smaller user modifications."
ITEM.model = "models/weapons/ethereal/w_m40.mdl"
ITEM.class = "cw_kk_ins2_m40a1"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 34000
ITEM.flag = "d"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 25
ITEM.weight = 6.57
ITEM.repairCost = ITEM.price/100*1