ITEM.name = "SVU"
ITEM.description = "The OTs-03 SVU is a bullpup configuration of the SVD sniper rifle. The SVU was developed to meet the needs of the security forces of the Russian Ministry of Internal Affairs, such as OMON. The SVU was first seen in use in the First Chechen War. Originally, the plan was to just slightly modernize the aging SVD, but the designers eventually realised that the configuration of the weapon would have to be completely altered, leading to the creation of the SVU."
ITEM.model = "models/weapons/ethereal/w_svu.mdl"
ITEM.class = "cw_kk_ins2_svu"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 80560
ITEM.flag = "Z"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 22
ITEM.weight = 3.6
ITEM.repairCost = ITEM.price/100*1