ITEM.name = "Sawed Off Ithaca 37"
ITEM.description = "The Ithaca 37 is a pump-action shotgun made in large numbers for the civilian, military, and police markets. It utilizes a novel combination ejection/loading port on the bottom of the gun which leaves the sides closed to the elements. Since shotshells load and eject from the bottom, operation of the gun is equally convenient for both right and left hand shooters. This particular shotgun has had the barrel sawn off to shorten its length."
ITEM.model = "models/weapons/ethereal/w_sawedithaca37.mdl"
ITEM.class = "cw_kk_ins2_sawedithaca37"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 6000
ITEM.flag = "C"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 20
ITEM.weight = 2.5
ITEM.repairCost = ITEM.price/100*1