CustomizableWeaponry:addFireSound("CW_KK_INS2_MP40_FIRE", "weapons/mp40/mp40_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_MP40_FIRE_SUPPRESSED", "weapons/mp40/mp40_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTBACK", "weapons/mp40/handling/mp40_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTLOCK", "weapons/mp40/handling/mp40_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_BOLTUNLOCK", "weapons/mp40/handling/mp40_boltunlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_EMPTY", "weapons/mp40/handling/mp40_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_FIRESELECT", "weapons/mp40/handling/mp40_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGHIT", "weapons/mp40/handling/mp40_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGIN", "weapons/mp40/handling/mp40_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGOUT", "weapons/mp40/handling/mp40_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MP40_MAGRELEASE", "weapons/mp40/handling/mp40_magrelease.wav")
