ITEM.name = "12g Slug"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "12 Gauge -SG-" // type of the ammo
ITEM.ammoAmount = 50 // amount of the ammo
ITEM.description= "A box that contains %s 12 gauge slug shells. "
ITEM.longdesc = "This heavy 12-caliber slug round is normally used for hunting big game, but is also good for other purposes."
ITEM.price = 700
ITEM.busflag = {"ammo2_1"}
ITEM.img = Material("vgui/hud/12gaugesg.png")