ITEM.name = ".410 Magnum Buck"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = ".45 ACP -41-" // type of the ammo
ITEM.ammoAmount = 50 // amount of the ammo
ITEM.description= "A box that contains %s .410 bore shells. "
ITEM.longdesc = "The .410 bore, is the second-smallest caliber of shotgun shell commonly available. A .410 bore shotgun loaded with shot shells is well suited for small game hunting and pest control."
ITEM.price = 600
ITEM.busflag = {"ammo2"}
ITEM.img = Material("vgui/hud/410buck.png")