CustomizableWeaponry:addFireSound("DOIMP40_FIRE", "weapons/doipack/mp40/mp40_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("DOIMP40_FIRE_SUPPRESSED", "weapons/doipack/mp40/mp40_suppressed_fp.wav", 1, 70, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIMP40_BOLTBACK", "weapons/doipack/mp40/handling/mp40_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_BOLTLOCK", "weapons/doipack/mp40/handling/mp40_boltlock.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_BOLTUNLOCK", "weapons/doipack/mp40/handling/mp40_boltunlock.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_MAGHIT", "weapons/doipack/mp40/handling/mp40_maghit.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_MAGIN", "weapons/doipack/mp40/handling/mp40_magin.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_MAGOUT", "weapons/doipack/mp40/handling/mp40_magout.wav")
CustomizableWeaponry:addReloadSound("DOIMP40_MAGRELEASE", "weapons/doipack/mp40/handling/mp40_magrelease.wav")
