CustomizableWeaponry:addFireSound("CW_KK_INS2_STERLING_FIRE", "weapons/sterling/sterling_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_STERLING_FIRE_SUPPRESSED", "weapons/sterling/sterling_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_BOLTBACK", "weapons/sterling/handling/sterling_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_BOLTLOCK", "weapons/sterling/handling/sterling_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_BOLTUNLOCK", "weapons/sterling/handling/sterling_boltunlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_EMPTY", "weapons/sterling/handling/sterling_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_FIRESELECT", "weapons/sterling/handling/sterling_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_MAGHIT", "weapons/sterling/handling/sterling_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_MAGIN", "weapons/sterling/handling/sterling_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_MAGOUT", "weapons/sterling/handling/sterling_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_MAGRELEASE", "weapons/sterling/handling/sterling_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_STOCKOPEN1", "weapons/sterling/handling/sterling_stockopen_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_STERLING_STOCKOPEN2", "weapons/sterling/handling/sterling_stockopen_02.wav")