ITEM.name = "Flash"
ITEM.model ="models/nasca/etherealsrp_artifacts/flash.mdl"
ITEM.description = "This artifact emits a lot of light."
ITEM.longdesc = "This artifact is very similar in appearance to Moonlight and resembles a plasma globe or a plasma lamp. When worn, it is known to slightly counter harmful effects of psy-anomalies or psy-waves of certain mutants. Flash acts as a powerful resistor and will absorb even lethal doses of electricity. On the other hand, it is extremely important to note that each time it comes into contact with electricity, it will release a static build-up which, while not deadly, can have an effect similar to a Taser shock. The artifact has weak regenerative properties and its direct touch has similar effect to a plasma globe, making one feel energized. However, it also hinders healing process, thus caution is advised especially when wounded or bleeding. This artifact is also extremely light and very portable. Rare artifact."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 15000
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5