ITEM.name = "Flame"
ITEM.model = "models/nasca/etherealsrp_artifacts/flame.mdl"
ITEM.description = "Flaming artifact."
ITEM.longdesc = "This artifact forms in areas of high thermal activity. Produces powerful infrared emissions which intensify metabolic processes, healing wounds before its bearer's very eyes. As this artifact is very rare, it is extremely valuable. As regards its effects, it is similar to the Eye in that it will reduce the temperature of user's body, which is especially useful when exposed to potent heat sources. It also acts as powerful resistor, and negates the effect of acids. Moreover, its healing capabilities are even stronger than in case of the Eye as stalkers in possession of this artifact are said to have survived being wounded by chimeras. Thanks to that, it has earned the reputation of a miraculous artifact. Many stalkers owe it their lives, and most veteran mutant hunters carry it in case they run into danger. However, it shares not only positive but also negative properties of its cousin: entering a toxic or chemical anomaly with this artifact on the belt is suicide. It will increase the corrosivity of chemical particles and enhance the adverse effect of the toxins within user's bloodstream. It can also be used as a reusable medkit of sorts since it heals wounds very quickly. Extremely rare."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 37500
ITEM.flag = "A"
ITEM.value = ITEM.price*0.5