CustomizableWeaponry:addFireSound("CW_KK_INS2_M45_FIRE", "weapons/m45/m45_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M45_FIRE_SUPPRESSED", "weapons/m45/m45_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_BOLTBACK", "weapons/m45/handling/m45_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_BOLTRELEASE", "weapons/m45/handling/m45_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_EMPTY", "weapons/m45/handling/m45_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_MAGHIT", "weapons/m45/handling/m45_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_MAGIN", "weapons/m45/handling/m45_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_MAGOUT", "weapons/m45/handling/m45_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_MAGRELEASE", "weapons/m45/handling/m45_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M45_SAFETY", "weapons/m45/handling/m45_safety.wav")