CustomizableWeaponry:addFireSound("CW_KK_INS2_UMP45_FIRE", "weapons/ump45/ump45_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_UMP45_FIRE_SUPPRESSED", "weapons/ump45/ump45_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_BOLTBACK", "weapons/ump45/handling/ump45_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_BOLTLOCK", "weapons/ump45/handling/ump45_boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_BOLTRELEASE", "weapons/ump45/handling/ump45_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_EMPTY", "weapons/ump45/handling/ump45_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_FIRESELECT", "weapons/ump45/handling/ump45_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_MAGIN", "weapons/ump45/handling/ump45_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_MAGOUT", "weapons/ump45/handling/ump45_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_UMP45_MAGRELEASE", "weapons/ump45/handling/ump45_magrelease.wav")