ITEM.name = "14.5x114mm Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_86x70_fmj.mdl"
ITEM.ammo = "14.5x114MM -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded 14.5x114mm ammo. "
ITEM.longdesc = "The 14.5x114mm round was originally developed for the PTRS and PTRD anti-tank rifles, but was later used as the basis for the KPV heavy machine gun that formed the basis of the ZPU series anti-aircraft guns that is also the main armament of the BTR series of armoured personnel carriers from the BTR-%s to the BTR-80."
ITEM.price = 8000
ITEM.flag = "0"
ITEM.width = 2
ITEM.height = 1
ITEM.Range = "x0.5"
ITEM.Dmg = -1
ITEM.Pen = -2