ITEM.name = ".338 Lapua Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_86x70_fmj.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = ".338 Lapua -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded .338 Lapua ammo. "
ITEM.longdesc = "The .338 Lapua Magnum is a specialized rimless bottlenecked centerfire cartridge developed for military long-range sniper rifles. The Afghanistan War and Iraq War made it a combat-proven round with ready and substantial ammunition availability. The .338 Lapua is a dual-purpose anti-personnel and anti-materiel round, but its anti-materiel potential is limited."
ITEM.price = 3500
ITEM.img = Material("vgui/hud/338lapuazl.png")
ITEM.Range = "x0.5"
ITEM.Dmg = -1
ITEM.Pen = -2