ITEM.name = ".44 Magnum Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_1143x23_fmj.mdl"
ITEM.ammo = ".44 Magnum -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded .44 Magnum ammo. "
ITEM.longdesc = "This large-bore .44 Magnum cartridge was originally designed for revolvers, but quickly adopted by rifles and carbines."
ITEM.price = 1000
ITEM.width = 2
ITEM.img = Material("vgui/hud/44magnumzl.png")