ITEM.name = "9x19mm Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_9x19_fmj.mdl"
ITEM.ammo = "9x19MM -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded 9x19mm ammo. "
ITEM.longdesc = "This basic 9x19 caliber round with a jacketed bullet has good characteristics while being simple to produce. The round is popular due to the fact that international conventions prohibit the use of expanding ammunition in combat. "
ITEM.price = 750
ITEM.img = Material("vgui/hud/9x19zl.png")
ITEM.Range = "x0.5"
ITEM.Dmg = -1
ITEM.Pen = -2