ITEM.name = "9x19mm +P+"
ITEM.model = "models/kek1ch/ammo_9x19_fmj.mdl"
ITEM.ammo = "9x19MM -AP-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x19mm armor piercing ammo. "
ITEM.longdesc = "placeholder. "
ITEM.price = 750
ITEM.busflag = {"ammo1"}
ITEM.img = Material("vgui/hud/9x19.png")
