ITEM.name = "Foregrip"
ITEM.description = "A stabilizing grip for the front of your weapon."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.attachName = "md_foregrip"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/grip.png")
ITEM.attachSlot = 3
--ITEM.busflag = "SPECIAL3"
ITEM.price = 3500
ITEM.repairCost = ITEM.price/100*1