ITEM.name = "Kobra sight"
ITEM.description = "Russian hybrid sight. T type sight."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/sights.png")
ITEM.model = "models/cw2/attachments/microt1.mdl"
ITEM.attachName = "md_kobra"
ITEM.attachSlot = 1
--ITEM.busflag = "SPECIAL3"
ITEM.price = 5000
ITEM.repairCost = ITEM.price/100*1
ITEM.Special = "+5 BAL"