ITEM.name = "SAKER suppressor"
ITEM.description = " A suppressor for larger caliber rifles of western origin."
ITEM.category = "Attachments"
ITEM.width = 2
ITEM.height = 1
ITEM.attachName = "md_saker"
ITEM.model = "models/cw2/attachments/cobra_m2.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/silenced.png")
ITEM.attachSlot = 2
--ITEM.busflag = "SPECIAL3_1_1"
ITEM.price = 5000
ITEM.repairCost = ITEM.price/100*1