ITEM.name = "Trijicon RMR"
ITEM.description = "Tiny holographic sight for pistols. Dot type sight."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.attachName = "md_rmr"
ITEM.model = "models/cw2/attachments/microt1.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/sights.png")
ITEM.attachSlot = 1
--ITEM.busflag = "SPECIAL3"
ITEM.price = 5000
ITEM.repairCost = ITEM.price/100*1
ITEM.Special = "+5 BAL"