ITEM.name = "Tundra suppressor"
ITEM.description = "A suppressor for small arms, mostly pistols and sub machine guns."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.attachName = "md_tundra9mm"
ITEM.model = "models/cw2/attachments/cobra_m2.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/silenced.png")
ITEM.attachSlot = 2
--ITEM.busflag = "SPECIAL3_1_1"
ITEM.price = 5000
ITEM.repairCost = ITEM.price/100*1