ITEM.name = "12g Tri-Ball"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "12 Gauge -TR-" // type of the ammo
ITEM.ammoAmount = 50 // amount of the ammo
ITEM.description= "A box that contains %s 12 gauge tri-ball shells. "
ITEM.longdesc = "Tri-Ball 12 gauge shell filled with %s mm shot. This round fires three large shots, with relatively high accuracy compared to other shells. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.price = 750
--ITEM.busflag = "SPECIAL8_1"
ITEM.img = Material("vgui/hud/12gauge.png")
ITEM.Dmg = 3
ITEM.weight = 0.045
ITEM.isAmmo = true