ITEM.name = "12g Buckshot"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "12 Gauge" // type of the ammo
ITEM.ammoAmount = 50 // amount of the ammo
ITEM.description= "A box that contains %s 12 gauge shells. "
ITEM.longdesc = "Standard 12 gauge shell filled with 6 mm shot. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.price = 600
ITEM.busflag = {"ammo2"}
ITEM.img = Material("vgui/hud/12gauge.png")
ITEM.weight = 0.045
ITEM.isAmmo = true