ITEM.name = "23mm Shells"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "23mm Shell"
ITEM.description = "A Box that contains 23mm Buckshot shells."
ITEM.category = "Ammunition"
ITEM.price = 970
ITEM.flag = "G"
ITEM.ammoAmount = 30
ITEM.weight = 0.1
ITEM.isAmmo = true