ITEM.name = ".38 Special"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 100
ITEM.ammo = ".38 Special" // type of the ammo
ITEM.description = "A Box that contains .38 Special"
ITEM.category = "Ammunition"
ITEM.price = 180
ITEM.busflag = "ammo1_1"
ITEM.weight = 0.023
ITEM.isAmmo = true