ITEM.name = ".38 Special"
ITEM.model = "models/ethprops/ammo/357.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 100
ITEM.ammo = ".38 Special" // type of the ammo
ITEM.description = "A Box that contains .38 Special"
ITEM.category = "Ammunition"
ITEM.price = 180
ITEM.flag = "g"
ITEM.weight = 0.023
ITEM.isAmmo = true