ITEM.name = "5.45x39mm Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_545x39_fmj.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "5.45x39MM -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded 5.45x39mm ammo. "
ITEM.longdesc = "Military 5.45x39 7H10 caliber is an improved piercing round for automatic rifles of Warsaw Pact countries. Provides better accuracy than the 7.62 caliber round thanks to reduced recoil and a 100 meter increase in range."
ITEM.price = 1500
ITEM.img = Material("vgui/hud/545x39zl.png")
ITEM.busflag = {"ammo3"}
ITEM.Range = "x0.5"
ITEM.Dmg = -1
ITEM.Pen = -2
ITEM.weight = 0.015
ITEM.isAmmo = true