ITEM.name = "7.62x51mm Belt"
ITEM.model = "models/kek1ch/ammo_pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x51MMB"
ITEM.description = "A Belt of 7.62x51mm"
ITEM.category = "Ammunition"
ITEM.price = 7250
ITEM.busflag = {"ammo5"}
ITEM.ammoAmount = 100
ITEM.weight = 0.033
ITEM.isAmmo = true