ITEM.name = "7.62x51mm Belt"
ITEM.model = "models/ethprops/ammo/pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x51MMB"
ITEM.description = "A Belt of 7.62x51mm"
ITEM.category = "Ammunition"
ITEM.price = 1385
ITEM.flag = "G"
ITEM.ammoAmount = 100
ITEM.weight = 0.033
ITEM.isAmmo = true