ITEM.name = "7.62x54mm Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_762x54_7h1.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMR -ZL-" // type of the ammo
ITEM.ammoAmount = 100 // amount of the ammo
ITEM.description= "A box that contains %s rounds of zone-loaded 7.62x54mm ammo. "
ITEM.longdesc = "Cheap 7.62 PP (also known as 7.62 R) is a dated rifle caliber introduced in the Soviet Empire at the turn of the 19th century and was still used by the USSR after World War II. It was originally designed for the Mosin-Nagant standard-issue infantry rifle and is quite common in the Zone due to the popularity of the rifle. The round is relatively cheap but has surprisingly good penetrative capabilities, even in comparison to more modern ammo types. It can also be used as a cheaper solution in the PKM machine gun."
ITEM.price = 2100
ITEM.width = 2
ITEM.height = 1
ITEM.busflag = {"ammo4"}
ITEM.img = Material("vgui/hud/762x54zl.png")
ITEM.Range = "x0.5"
ITEM.Dmg = -1
ITEM.Pen = -2
ITEM.weight = 0.039
ITEM.isAmmo = true