ITEM.name = "M203 Grenade"
ITEM.model = ("models/weapons/upgrades/a_projectile_m203.mdl")
ITEM.description = "An M203 Grenade, made specifically to be launched from NATO Grenade Launchers."
ITEM.price = 3000
ITEM.busflag = {"ammo5_1"}
ITEM.category = "Ammunition"
ITEM.ammo = "40MM"
ITEM.ammoAmount = 3
ITEM.weight = 0.23
ITEM.isAmmo = true