ITEM.name = "PG-7VM Grenade"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.ammo = "PG-7VM Grenade" // type of the ammo
ITEM.ammoAmount = 1 // amount of the ammo
ITEM.description= "Ammo for an RPG-7"
ITEM.longdesc = "It's a PG-7VM Grenade, a rocket propelled grenade. It shears through metal with a shaped charge. Basically fucks anything it comes in contact with."
ITEM.price = 600
ITEM.busflag = {"ammo"}
ITEM.img = Material("vgui/hud/ammo23.png")
ITEM.weight = 3
ITEM.isAmmo = true