CustomizableWeaponry:addFireSound("CW_KK_INS2_M14WOOD_FIRE", "weapons/m14wood/m1carbine_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_M14WOOD_FIRE_SUPPRESSED", "weapons/m14wood/m14_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_BOLTBACK", "weapons/m14wood/handling/m14_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_BOLTRELEASE", "weapons/m14wood/handling/m14_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_EMPTY", "weapons/m14wood/handling/m14_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_FIRESELECT", "weapons/m14wood/handling/m14_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_MAGIN", "weapons/m14wood/handling/m14_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_MAGOUT", "weapons/m14wood/handling/m14_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_MAGOUTRATTLE", "weapons/m14wood/handling/m14_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_MAGRELEASE", "weapons/m14wood/handling/m14_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M14WOOD_RATTLE", "weapons/m14wood/handling/m14_rattle.wav")