ITEM.name = "Burer's Brain"
ITEM.model ="models/kek1ch/item_controller_brain.mdl"
ITEM.description = "The brain of a burer."
ITEM.longdesc = "Burers have potent mental powers and it's safe to say that these powers have their origin in their brain. What's interesting, every mutant possessing abilities related to psy waves has a brain of similar structure."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10000
ITEM.flag = "A"
ITEM.value = ITEM.price*1*1
ITEM.weight = 0.25