ITEM.name = "Controller's hand"
ITEM.model ="models/kek1ch/hand_kontroler.mdl"
ITEM.description = "The hand of a dead controller."
ITEM.longdesc = "The controller seems to use its hand when mentally attacking its prey. The scientists will gladly examine it in the hope of finding the source of mutation responsible for its psy-related powers. Smells like old socks and bad kimchee."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "A"
ITEM.value = ITEM.price*1*1
ITEM.weight = 1