CustomizableWeaponry:addFireSound("CW_KK_INS2_MAKAROV_FIRE", "weapons/makarov/makarov_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_MAKAROV_FIRE_SUPPRESSED", "weapons/makarov/makarov_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_BOLTBACK", "weapons/makarov/handling/makarov_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_BOLTRELEASE", "weapons/makarov/handling/makarov_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_EMPTY", "weapons/makarov/handling/makarov_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_MAGHIT", "weapons/makarov/handling/makarov_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_MAGIN", "weapons/makarov/handling/makarov_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_MAGOUT", "weapons/makarov/handling/makarov_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_MAGRELEASE", "weapons/makarov/handling/makarov_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROV_SAFETY", "weapons/makarov/handling/makarov_safety.wav")