ITEM.name = "King Arms MR"
ITEM.description = "Taiwanese reflex sight. T type sight."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.attSearch = { "md_reflex",}
ITEM.model = "models/cw2/attachments/microt1.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/sights.png")
ITEM.slot = 1
--ITEM.busflag = "SPECIAL3"
ITEM.price = 5000
ITEM.repairCost = ITEM.price/100*1
ITEM.Special = "+5 BAL"
ITEM.isAttachment = true
ITEM.weight = 0.205