ITEM.name = "Schmidt Shortdot"
ITEM.description = "German optic sight. 2.5x magnification. Cross type sight."
ITEM.category = "Attachments"
ITEM.width = 2
ITEM.height = 1
ITEM.attachName = "md_schmidt_shortdot"
ITEM.model = "models/cw2/attachments/pso.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/2,5xmag.png")
ITEM.slot = 1
--ITEM.busflag = "SPECIAL3_1"
ITEM.price = 6000
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 20
ITEM.Special = "+20 to CALLED SHOT"
ITEM.isAttachment = true
ITEM.weight = 0.5