ITEM.name = "AK-103"
ITEM.description = "The AK-103 assault rifle is a derivative of the AK-74M chambered for the 7.62×39mm M43 round, similar to the older AKM. The AK-103 can be fitted with a variety of sights, including night vision and telescopic sights, plus a knife-bayonet or a grenade launcher. It uses plastic components where possible instead of wood or metal, with such components being the pistol grip, handguards and stock."
ITEM.model = "models/weapons/ethereal/w_f_ak103.mdl"
ITEM.class = "cw_kk_ins2_ak103"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 33750
ITEM.flag = "b"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 3.4
ITEM.repairCost = ITEM.price/100*1
ITEM.busflag = {"guns4_1"}
ITEM.Range = 75
ITEM.RoF = "S/3/6"
ITEM.Dmg = "1d10+3"
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.Rld = "Ready"