ITEM.name = "AK-74 Zenith"
ITEM.description = "The AK-74 is an assault rifle developed in the early 1970s by Russian designer Mikhail Kalashnikov as the replacement for the earlier AKM (itself a refined version of the AK-47). It uses a smaller 5.45×39mm cartridge, replacing the 7.62×39mm chambering of earlier Kalashnikov-pattern weapons."
ITEM.model = "models/weapons/ethereal/w_ak74z.mdl"
ITEM.class = "cw_kk_ins2_ak74z"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 18500
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 3.3
ITEM.repairCost = ITEM.price/100*1
ITEM.busflag = {"guns4"}