ITEM.name = "AK Alfa"
ITEM.description = "The AK-Alfa rifle is an interesting attempt to upgrade ergonomics and handling characteristics of famous Kalashnikov AK-type weapons while maintaining their remarkable reliability and simplicity of use. Fires 5.56x45 Rounds."
ITEM.model = "models/weapons/ethereal/w_alfa.mdl"
ITEM.class = "cw_kk_ins2_akalfa"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 66235
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 3.5
ITEM.repairCost = ITEM.price/100*1