ITEM.name = "AK-105"
ITEM.description = "The AK-105 is a shortened carbine version of the AK-74M rifle, which in turn was derived from the original AK-47 design and its AK-74 successor. The AK-102, AK-104, and AK-105 are very similar in design, the only difference being the caliber and corresponding magazine type. The AK-105 is chambered to fire 5.45×39mm ammunition"
ITEM.model = "models/weapons/ethereal/w_f_ak105.mdl"
ITEM.class = "cw_kk_ins2_ak105"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 35050
ITEM.flag = "b"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 3.2
ITEM.repairCost = ITEM.price/100*1