ITEM.name = "BR-99"
ITEM.description = "A modified AR-15, the BR-99 is a 12 gauge shotgun featuring all of the reliability, comfort, and versatility of the AR platform. With fire select, this shotgun can either be semi- or fully automatic."
ITEM.model = "models/weapons/ethereal/w_br99.mdl"
ITEM.class = "cw_kk_ins2_br99"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 91600
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 30
ITEM.weight = 4.4
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 50
ITEM.RoF = "S/3/-"
ITEM.Dmg = "1d10+4"
ITEM.Pen = 2
ITEM.Mag = 10
ITEM.Rld = "2 Ready"
ITEM.Special = "Buckshot"
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 4.2