ITEM.name = "CZ-75"
ITEM.description = "The CZ 75 is a semi-automatic pistol made by Czech firearm manufacturer ČZUB. First introduced in 1975, it is one of the original 'wonder nines' featuring a staggered-column magazine, all-steel construction, and a hammer forged barrel. It is widely distributed throughout the world and is the most common handgun in the Czech Republic. Fires 9x19 rounds."
ITEM.model = "models/weapons/ethereal/w_cz75.mdl"
ITEM.class = "cw_kk_ins2_cz75"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 6550
ITEM.flag = "b"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_R_Thigh",
	ang = Angle(-0, -0,90),
	pos = Vector(-6, 8, -4),
}
ITEM.modifier = 11
ITEM.weight = 1.12
ITEM.repairCost = ITEM.price/100*1
ITEM.busflag = {"guns1_1_1"}