ITEM.name = "Groza"
ITEM.description = "The OTs-14 Groza is a Russian selective fire bullpup assault rifle chambered for the 7.62×39 round and the 9×39mm subsonic round. It was developed in the 1990s at the TsKIB SOO in Tula, Russia. The weapon is colloquially known as OC-14 or OTs-14 'Groza'. This one is chambered in 7.62x39mm."
ITEM.model = "models/weapons/ethereal/item_groza1.mdl"
ITEM.class = "cw_kk_ins2_groza1"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 41500
ITEM.busflag = {"guns4_1_1"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 2.7
ITEM.repairCost = ITEM.price/100*1