ITEM.name = "M4A1"
ITEM.description = "The M4A1 carbine is a fully automatic variant of the basic M4 carbine intended for special operations use. The M4A1 was introduced in May 1991, and was in service in 1994. The M4A1 has a 'S-1-F' (safe/semi-automatic/fully automatic) trigger group, while the M4 has a 'S-1-3' (safe/semi-automatic/3-round burst) trigger group. Fires 5.56x45 rounds."
ITEM.model = "models/weapons/ethereal/w_m4a1.mdl"
ITEM.class = "cw_kk_ins2_m4a1"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 56000
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 7
ITEM.weight = 6.570
ITEM.repairCost = ITEM.price/100*1
ITEM.busflag = {"guns5_1_1"}
ITEM.Range = 100
ITEM.RoF = "S/3/6"
ITEM.Dmg = "1d10+3"
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.Rld = "Ready"