ITEM.name = "S&W M10 Snub Nose"
ITEM.description = "The Smith & Wesson Model 10 is a revolver of worldwide popularity. It was the successor to the Smith & Wesson .32 Hand Ejector Model of 1896 and was the first Smith & Wesson revolver to feature a cylinder release latch on the left side of the frame like the Colt M1889. In production since 1899, it is a six-shot double-action .38 revolver with fixed sights. This particular one is a snub-nose chrome version."
ITEM.model = "models/weapons/ethereal/w_m10.mdl"
ITEM.class = "cw_kk_ins2_m10"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3750
ITEM.busflag = {"guns3"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_R_Thigh",
	ang = Angle(-0, -0,90),
	pos = Vector(-6, 8, -4),
}
ITEM.modifier = 2
ITEM.weight = 0.7
ITEM.repairCost = ITEM.price/100*1