ITEM.name = "M45"
ITEM.description = "The M45 MEUSOC is a magazine-fed, recoil-operated, single-action, semiautomatic pistol chambered for the .45 ACP cartridge. It's a variant of the M1911, and has been the standard-issue side arm for the Force Recon Element of the United States Marine Corps' Marine Expeditionary Units since 1985."
ITEM.model = "models/weapons/ethereal/w_m45.mdl"
ITEM.class = "cw_kk_ins2_m45"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7200
ITEM.busflag = {"guns3_1"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_R_Thigh",
	ang = Angle(-0, -0,90),
	pos = Vector(-6, 8, -4),
}
ITEM.modifier = 13
ITEM.weight = 1.105
ITEM.repairCost = ITEM.price/100*1