ITEM.name = "OTs-33 Pernach"
ITEM.description = "The OTs-33 Pernach is a Russian 9x18 Makarov machine pistol, derived from the 5.45mm OTs-23 Drotik machine pistol. The Pernach is an automatic pistol designed to replace the Stechkin APS in various special OMON units within the Russian police, the Russian Ministry of Internal Affairs (MVD) and other paramilitary units."
ITEM.model = "models/weapons/ethereal/w_pernach.mdl"
ITEM.class = "cw_kk_ins2_pernach"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3250
ITEM.busflag = {"guns1"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_R_Thigh",
	ang = Angle(-0, -0,90),
	pos = Vector(-6, 8, -4),
}
ITEM.modifier = 4
ITEM.weight = 1.3
ITEM.repairCost = ITEM.price/100*1
ITEM.RoF = "S/3/6"
ITEM.Dmg = "1d10+2"
ITEM.Pen = 6
ITEM.Mag = 18
ITEM.Rld = "Ready"
ITEM.Special = "CQC"