ITEM.name = "RPK-74M"
ITEM.description = "The RPK-74 was introduced in 1974 together with the AK-74 assault rifle and chambered for the new 5.45×39mm intermediate cartridge. It was derived from the AK-74 rifle, with modifications that mirror those made to the AKM to create the RPK. It also uses a longer and heavier chrome-plated barrel, bipod, adjusted gas channel in the gas block, and a different front sight tower."
ITEM.model = "models/weapons/ethereal/w_f_rpk74m.mdl"
ITEM.class = "cw_kk_ins2_rpk74m"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 31250
ITEM.flag = "b"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 5
ITEM.weight = 4.4