ITEM.name = "SCAR-H"
ITEM.description = "The FN SCAR is a gas-operated self-loading rifle with a rotating bolt. It is constructed to be extremely modular, including barrel change to switch between calibers. The rifle was developed by Belgian manufacturer FN Herstal (FNH) for the United States Special Operations Command (SOCOM) to satisfy the requirements of the SCAR competition. The 'H' varient is chambered for 7.62x51mm Rounds, and includes a longer barrel for accuracy at long range."
ITEM.model = "models/weapons/ethereal/w_sca.mdl"
ITEM.class = "cw_kk_ins2_scarh"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 98600
ITEM.busflag = {"guns7_1_1"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 28
ITEM.weight = 3.720
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 175
ITEM.RoF = "S/3/6"
ITEM.Dmg = "1d10+3"
ITEM.Pen = 12
ITEM.Mag = 20
ITEM.Rld = "Ready"