ITEM.name = "SPAS-12"
ITEM.description = "The appearance and intended purpose of the SPAS-12 initially led to its 'military' designation as a combat shotgun. The SPAS-12 was designed from the ground up as a rugged military shotgun, and it was named the Special Purpose Automatic Shotgun. In 1990, Franchi renamed the shotgun the Sporting Purpose Automatic Shotgun, which allowed continued sales to the United States as a limited-magazine-capacity, fixed-stock model until 1994. Fires 12 Gauge Shells."
ITEM.model = "models/weapons/ethereal/w_spas12.mdl"
ITEM.class = "cw_kk_ins2_spas12"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 62150
ITEM.busflag = {"guns2_1_1"}
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.holsterDrawInfo = {
	bone = "ValveBiped.Bip01_Spine2",
	ang = Angle(180, 0,20),
	pos = Vector(4, 10, -2),
}
ITEM.modifier = 20
ITEM.weight = 4.4
ITEM.repairCost = ITEM.price/100*1