CustomizableWeaponry:addFireSound("CW_KK_INS2_MAKAROVCHAN_FIRE", "weapons/makarovchan/moan_fire.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_MAKAROVCHAN_FIRE_SUPPRESSED", "weapons/makarovchan/moan_fire.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_BOLTBACK", "weapons/makarovchan/handling/makarov_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_BOLTRELEASE", "weapons/makarovchan/handling/makarov_boltrelease_oniichan.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_EMPTY", "weapons/makarovchan/handling/makarov_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_MAGHIT", "weapons/makarovchan/handling/makarov_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_MAGIN", "weapons/makarovchan/handling/makarov_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_MAGOUT", "weapons/makarovchan/handling/makarov_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_MAGRELEASE", "weapons/makarovchan/handling/makarov_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MAKAROVCHAN_SAFETY", "weapons/makarovchan/handling/makarov_safety.wav")