ITEM.name = "Bone Cluster"
ITEM.model ="models/lostsignalproject/items/artefacts/cocoon.mdl"
ITEM.description = "A cluster of interconnected bone tissue."
ITEM.longdesc = "The structure of the artifact, seems to resemble some sort of unnattural cancerous bone growth, warped and twisted by some terrible force. It is unknown where this artifact comes from, as it has been observed near almost every kind of anomaly, although mostly around the chemical types. It is a quite common artifact, without any observable special properties, however its strange structure and the fact that it seems to be human bone mass that is warped into this grotesque shape interests scientists."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1900
ITEM.flag = "A"
ITEM.rarity = 1
ITEM.baseweight = 0.290
ITEM.varweight  = 0.025
