ITEM.name = "Cell"
ITEM.model ="models/lostsignalproject/items/artefacts/cell.mdl"
ITEM.description = "A hard, perforated sphere, with a squishy mass inside."
ITEM.longdesc = "This artifact is a quite common find in the Zone, however that does not mean that scientists aren't interested in it. From what is currently known, the gooey mass performs a nuclear reaction, spltting the atoms of whatever is inside the hard shell, and converting it into the simplest element, hydrogen. The rate at which this happens is quite slow, however, and as such a large amount of these are needed."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7500
ITEM.flag = "A"
ITEM.rarity = 3
ITEM.baseweight = 1.000
ITEM.varweight  = 0.200
