ITEM.name = "Mica"
ITEM.model ="models/lostsignalproject/items/artefacts/mica.mdl"
ITEM.description = "A hollowed out shell of stone, with a hard, slightly rubbery black mass coating the insides."
ITEM.longdesc = "This artifact seems to be a rarer variant of the 'Slug' artifact, however the conditions under which it is formed are not known. The inner black mass seems to breathe and throb regularly, and will respond to being touched and shaken. Scientists are very interested in this specimen, as it seems to be some sort of unknown lifeform."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10750
ITEM.flag = "A"
ITEM.rarity = 5
ITEM.baseweight = 4.900
ITEM.varweight  = 0.400
