ITEM.name = "Battery"
ITEM.model ="models/nasca/etherealsrp_artifacts/battery.mdl"
ITEM.description = "An electric artifact."
ITEM.longdesc = "A heavy artifact with a unique geometrical shape, consisting of three bent bars connected to either end of the artifact. It is possible to attach power lines to the artifact, and when done, it outputs a low voltage current, however in the samples tested by scientists, there was seemingly no limit to the amperage of the current.\nScientists are very interested in this, as it could revolutionise battery and power generation technology."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8400
ITEM.JumpPower = 7000
ITEM.flag = "A"
ITEM.rarity = 4
ITEM.baseweight = 6.000
ITEM.varweight  = 2.500
