ITEM.name = "Crystal"
ITEM.model ="models/lostsignalproject/items/artefacts/crystal.mdl"
ITEM.description = "A large red crystal."
ITEM.longdesc = "A beautiful red crystal. The crystalline structure is similar to quartz, and in general it is very similar to Carnelian crystal in appearance. Outside of the gorgeous color and the almost flawless structure with few imperfections, scientists have discovered that it is incredibly pure, and that the red color is not from a ferric oxide impurity as in Carnelian. This makes it fairly valuable in the semiconductor industry. It is also in demand with regular collectors, as few can resist its alluring glow."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 11400
ITEM.flag = "A"
ITEM.rarity = 5
ITEM.baseweight = 9.500
ITEM.varweight  = 0.550
