CustomizableWeaponry:addFireSound("CW_KK_INS2_DEAGLE_FIRE", "weapons/cw_kk_ins2_deagle/deagle_fp.wav")
CustomizableWeaponry:addFireSound("CW_KK_INS2_DEAGLE_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_deagle/deagle_suppressed_fp.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_BOLTBACK", "weapons/cw_kk_ins2_deagle/handling/deagle_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_BOLTRELEASE", "weapons/cw_kk_ins2_deagle/handling/deagle_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_EMPTY", "weapons/cw_kk_ins2_deagle/handling/deagle_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGHIT", "weapons/cw_kk_ins2_deagle/handling/deagle_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGIN", "weapons/cw_kk_ins2_deagle/handling/deagle_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGOUT", "weapons/cw_kk_ins2_deagle/handling/deagle_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGRELEASE", "weapons/cw_kk_ins2_deagle/handling/deagle_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_SAFETY", "weapons/cw_kk_ins2_deagle/handling/deagle_safety.wav")